# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ingrl1SwTZ3GolfYRy7hf2CmepYi0AyQ
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime
import tempfile
import os
from fpdf import FPDF

# --- CONFIGURAÇÃO INICIAL ---
st.set_page_config(
    page_title="Controle de Pagamentos",
    page_icon="💲",
    layout="wide"
)

# --- ESTILOS CSS (Refinado) ---
st.markdown("""
    <style>
    .report-container {
        background-color: white;
        padding: 2rem;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        border: 1px solid #f0f0f0;
    }
    .kpi-card {
        background-color: #f8f9fa;
        border-radius: 8px;
        padding: 15px;
        border-left: 5px solid #3b82f6;
    }
    .big-number { font-size: 24px; font-weight: bold; color: #1f2937; }
    .small-label { font-size: 14px; color: #6b7280; font-weight: 500; }
    </style>
""", unsafe_allow_html=True)

# --- FUNÇÕES DE UTILIDADE ---
def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def limpar_valor_moeda(valor):
    if isinstance(valor, (int, float)): return abs(float(valor))
    if isinstance(valor, str):
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: return abs(float(limpo))
        except: return 0.0
    return 0.0

def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith(('.xlsx', '.xls')):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except: return None

def selecionar_coluna(df, label, key_suffix, keywords):
    """Tenta adivinhar a coluna, mas permite troca manual"""
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break

    key = f"sel_{key_suffix}"
    # Se não existir no session state, inicializa
    if key not in st.session_state:
        st.session_state[key] = cols[default_idx] if cols else None

    # O selectbox atualiza o session_state automaticamente
    selected = st.selectbox(f"{label}", cols, index=default_idx, key=key)
    return selected

# --- CLASSE PDF PROFISSIONAL (CORRIGIDA) ---
class PDFProfissional(FPDF):
    def __init__(self, logo_path=None, periodo=""):
        super().__init__()
        self.logo_path = logo_path
        self.periodo = periodo

    def header(self):
        # Fundo do cabeçalho
        self.set_fill_color(245, 247, 250)
        self.rect(0, 0, 210, 40, 'F')

        # Logo
        if self.logo_path:
            try:
                self.image(self.logo_path, 10, 8, 30)
            except: pass

        # Título
        self.set_font('Arial', 'B', 18)
        self.set_xy(50, 10)
        self.cell(0, 10, 'Relatorio de Contas Pagas e A Pagar', 0, 1, 'L')

        # Subtítulo (Período)
        self.set_font('Arial', '', 10)
        self.set_text_color(100, 100, 100) # CORRIGIDO: set_textcolor -> set_text_color
        self.set_xy(50, 20)
        self.cell(0, 10, f'Periodo: {self.periodo}', 0, 1, 'L')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128) # CORRIGIDO
        self.cell(0, 10, f'Pagina {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(31, 41, 55) # CORRIGIDO
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_draw_color(59, 130, 246)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def kpi_card(self, label, value, x, y):
        self.set_xy(x, y)
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(220, 220, 220)
        self.rect(x, y, 60, 25, 'FD')

        self.set_xy(x + 2, y + 5)
        self.set_font('Arial', '', 9)
        self.set_text_color(100) # CORRIGIDO
        self.cell(56, 5, label, 0, 1, 'C')

        self.set_xy(x + 2, y + 12)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(0) # CORRIGIDO
        self.cell(56, 8, value, 0, 1, 'C')

    def create_table(self, df):
        # Header Tabela
        self.set_font('Arial', 'B', 10)
        self.set_fill_color(59, 130, 246)
        self.set_text_color(255) # CORRIGIDO

        col_widths = [100, 40, 50]
        headers = df.columns

        for i, h in enumerate(headers):
            self.cell(col_widths[i], 8, str(h), 1, 0, 'C', 1)
        self.ln()

        # Linhas
        self.set_font('Arial', '', 9)
        self.set_text_color(0) # CORRIGIDO
        fill = False
        for _, row in df.iterrows():
            self.set_fill_color(240, 245, 255) if fill else self.set_fill_color(255)

            txt_0 = str(row[0])[:45]
            try: txt_0 = txt_0.encode('latin-1', 'replace').decode('latin-1')
            except: pass

            txt_1 = str(row[1])
            txt_2 = str(row[2])

            self.cell(col_widths[0], 8, txt_0, 1, 0, 'L', fill)
            self.cell(col_widths[1], 8, txt_1, 1, 0, 'C', fill)
            self.cell(col_widths[2], 8, txt_2, 1, 1, 'R', fill)
            fill = not fill

# --- INTERFACE E LÓGICA ---

# Sidebar - Controle Principal
with st.sidebar:
    st.header("1. Arquivos")
    uploaded_logo = st.file_uploader("Logo da Empresa (Opcional)", type=['png', 'jpg'])
    uploaded_pagas = st.file_uploader("Relatório: PAGAS", type=['csv', 'xlsx'])
    uploaded_apagar = st.file_uploader("Relatório: A PAGAR", type=['csv', 'xlsx'])

    st.divider()

    # Switch de modo apresentação
    mode_apresentacao = st.toggle("📺 Modo Apresentação", value=False)

# VARIÁVEIS DE ESTADO
if 'processed_data' not in st.session_state:
    st.session_state.processed_data = None

# --- PROCESSAMENTO DOS DADOS ---
if not mode_apresentacao and uploaded_pagas and uploaded_apagar:

    # CONFIGURAÇÃO DE COLUNAS - AGORA NA SIDEBAR
    with st.sidebar.expander("⚙️ Configurar Colunas", expanded=False):
        st.markdown("**1. Contas Pagas**")
        df_pagas = carregar_dados(uploaded_pagas)
        if df_pagas is not None:
            col_p_data = selecionar_coluna(df_pagas, "Data Pagamento", "p_data", ['data', 'pagamento'])
            col_p_val = selecionar_coluna(df_pagas, "Valor", "p_val", ['valor', 'pago', 'total'])
            col_p_desc = selecionar_coluna(df_pagas, "Fornecedor", "p_desc", ['fornecedor', 'nome', 'descrição'])
            col_p_cat = selecionar_coluna(df_pagas, "Categoria (Opcional)", "p_cat", ['categoria', 'classificação'])

        st.divider()

        st.markdown("**2. Contas a Pagar**")
        df_apagar = carregar_dados(uploaded_apagar)
        if df_apagar is not None:
            col_a_data = selecionar_coluna(df_apagar, "Data Vencimento", "a_data", ['vencimento', 'data'])
            col_a_val = selecionar_coluna(df_apagar, "Valor", "a_val", ['valor', 'líquido', 'aberto'])
            col_a_desc = selecionar_coluna(df_apagar, "Fornecedor", "a_desc", ['fornecedor', 'nome', 'descrição'])

    # Lógica de Processamento
    if df_pagas is not None and df_apagar is not None:
        try:
            # Tratamento Pagas
            df_pagas[col_p_data] = pd.to_datetime(df_pagas[col_p_data], dayfirst=True, errors='coerce')
            df_pagas['valor_final'] = df_pagas[col_p_val].apply(limpar_valor_moeda)
            df_pagas = df_pagas.dropna(subset=[col_p_data])

            # Data Automática
            if not df_pagas.empty:
                min_pagas = df_pagas[col_p_data].min()
                max_pagas = df_pagas[col_p_data].max()
                str_periodo_pagas = f"{min_pagas.strftime('%d/%m')} a {max_pagas.strftime('%d/%m')}"
            else:
                str_periodo_pagas = "N/A"

            # Tratamento A Pagar
            df_apagar[col_a_data] = pd.to_datetime(df_apagar[col_a_data], dayfirst=True, errors='coerce')
            df_apagar['valor_final'] = df_apagar[col_a_val].apply(limpar_valor_moeda)
            df_apagar = df_apagar.dropna(subset=[col_a_data])

            # Data Automática
            if not df_apagar.empty:
                min_apagar = df_apagar[col_a_data].min()
                max_apagar = df_apagar[col_a_data].max()
                str_periodo_apagar = f"{min_apagar.strftime('%d/%m')} a {max_apagar.strftime('%d/%m')}"
            else:
                str_periodo_apagar = "N/A"

            # Salva no Session State
            st.session_state.processed_data = {
                'pagas': df_pagas,
                'apagar': df_apagar,
                'cols_p': {'data': col_p_data, 'val': 'valor_final', 'desc': col_p_desc, 'cat': col_p_cat},
                'cols_a': {'data': col_a_data, 'val': 'valor_final', 'desc': col_a_desc},
                'periodo_txt': f"{str_periodo_pagas} (Realizado) vs {str_periodo_apagar} (Previsto)",
                'dates': {'p_str': str_periodo_pagas, 'a_str': str_periodo_apagar},
                'totals': {
                    'pago': df_pagas['valor_final'].sum(),
                    'apagar': df_apagar['valor_final'].sum()
                }
            }
        except Exception as e:
            st.error(f"Erro ao processar dados. Verifique se as colunas selecionadas contêm datas e valores válidos.")

# --- RENDERIZAÇÃO ---

data = st.session_state.processed_data

if data:
    # Filtros Globais (Só mostra no modo normal)
    df_p = data['pagas'].copy()
    if not mode_apresentacao and data['cols_p']['cat'] in df_p.columns:
        st.sidebar.divider()
        st.sidebar.markdown("🔎 **Filtros**")
        cats = sorted(list(df_p[data['cols_p']['cat']].astype(str).unique()))
        sel_cat = st.sidebar.multiselect("Filtrar Categoria", cats)
        if sel_cat:
            df_p = df_p[df_p[data['cols_p']['cat']].astype(str).isin(sel_cat)]

    # Recalcula totais
    total_pago = df_p['valor_final'].sum()
    total_apagar = data['totals']['apagar']

    # --- LAYOUT DO RELATÓRIO ---
    with st.container():
        if mode_apresentacao:
            st.markdown("### 📺 Modo Apresentação")
            st.markdown(f"# Resultados Financeiros")
            st.markdown(f"*{data['periodo_txt']}*")
        else:
            # TÍTULO ALTERADO CONFORME SOLICITADO
            st.markdown(f"## 📑 Controle de Pagamentos Semanal")
            st.markdown(f"**Período:** {data['periodo_txt']}")

        st.markdown("---")

        # 1. KPIs Cards
        k1, k2, k3 = st.columns(3)
        diff = total_apagar - total_pago

        with k1:
            st.markdown(f"""
            <div class="kpi-card">
                <div class="small-label">TOTAL PAGO ({data['dates']['p_str']})</div>
                <div class="big-number" style="color:#10b981">{formatar_moeda_br(total_pago)}</div>
            </div>""", unsafe_allow_html=True)

        with k2:
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: #f59e0b;">
                <div class="small-label">A PAGAR ({data['dates']['a_str']})</div>
                <div class="big-number" style="color:#d97706">{formatar_moeda_br(total_apagar)}</div>
            </div>""", unsafe_allow_html=True)

        with k3:
            lbl_diff = "AUMENTO DE FLUXO" if diff > 0 else "REDUÇÃO DE FLUXO"
            cor_diff = "#ef4444" if diff > 0 else "#10b981"
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: {cor_diff};">
                <div class="small-label">COMPARAÇÃO ({lbl_diff})</div>
                <div class="big-number" style="color:{cor_diff}">{formatar_moeda_br(abs(diff))}</div>
            </div>""", unsafe_allow_html=True)

        st.write("")

        # 2. Gráficos
        g1, g2 = st.columns(2)
        with g1:
            st.subheader("Evolução Pagamentos")
            if not df_p.empty:
                chart_p = alt.Chart(df_p).mark_bar(color='#10b981', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_p']['data'], axis=alt.Axis(format='%d/%m', title='Data')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_p']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_p, use_container_width=True)
            else:
                st.info("Sem dados para exibir.")

        with g2:
            st.subheader("Previsão de Saídas")
            if not data['apagar'].empty:
                chart_a = alt.Chart(data['apagar']).mark_bar(color='#f59e0b', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_a']['data'], axis=alt.Axis(format='%d/%m', title='Vencimento')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_a']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_a, use_container_width=True)
            else:
                st.info("Sem dados para exibir.")

        # 3. Rankings
        st.divider()
        r1, r2 = st.columns(2)

        with r1:
            st.markdown("#### 🏆 Top 5 Fornecedores Pagos")
            if not df_p.empty:
                top_p = df_p.groupby(data['cols_p']['desc'])['valor_final'].sum().nlargest(5).reset_index()
                st.dataframe(top_p.style.format({'valor_final': 'R$ {:,.2f}'}), hide_index=True, use_container_width=True)
            else:
                st.caption("Sem dados.")
                top_p = pd.DataFrame()

        with r2:
            st.markdown("#### ⚠️ Top 5 Contas a Vencer")
            if not data['apagar'].empty:
                top_a = data['apagar'].nlargest(5, 'valor_final')[[data['cols_a']['data'], data['cols_a']['desc'], 'valor_final']].copy()
                top_a['Data'] = top_a[data['cols_a']['data']].dt.strftime('%d/%m')
                display_a = top_a[['Data', data['cols_a']['desc'], 'valor_final']].rename(columns={data['cols_a']['desc']: 'Fornecedor', 'valor_final': 'Valor'})
                st.dataframe(display_a.style.format({'Valor': 'R$ {:,.2f}'}), hide_index=True, use_container_width=True)
            else:
                st.caption("Sem dados.")
                display_a = pd.DataFrame()

    # --- ÁREA EXCLUSIVA: PDF E WHATSAPP ---
    if not mode_apresentacao:
        st.divider()
        st.subheader("📤 Exportação e Envio")

        tab_pdf, tab_wpp = st.tabs(["📄 Gerar PDF Profissional", "📱 Texto WhatsApp"])

        with tab_pdf:
            st.write("Gere um documento oficial para arquivamento ou envio por e-mail.")
            if st.button("Baixar Relatório em PDF"):
                try:
                    # Salva logo temporária se existir
                    logo_temp_path = None
                    if uploaded_logo:
                        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                            tmp.write(uploaded_logo.getvalue())
                            logo_temp_path = tmp.name

                    # Cria PDF
                    pdf = PDFProfissional(logo_temp_path, data['periodo_txt'])
                    pdf.add_page()

                    # KPIs no PDF
                    pdf.kpi_card("TOTAL PAGO", formatar_moeda_br(total_pago), 10, 50)
                    pdf.kpi_card("A PAGAR", formatar_moeda_br(total_apagar), 75, 50)
                    pdf.kpi_card("VARIACAO", formatar_moeda_br(abs(diff)), 140, 50)
                    pdf.ln(40)

                    # Tabela Pagos
                    pdf.chapter_title("Maiores Pagamentos Realizados")
                    if not top_p.empty:
                        top_5_pdf = top_p.copy()
                        top_5_pdf.columns = ['Fornecedor', 'Valor']
                        top_5_pdf['Tipo'] = 'Pago'
                        top_5_pdf['Valor'] = top_5_pdf['Valor'].apply(formatar_moeda_br)
                        pdf.create_table(top_5_pdf[['Fornecedor', 'Tipo', 'Valor']])
                    else:
                        pdf.set_font("Arial", "", 10)
                        pdf.cell(0, 10, "Sem dados neste periodo.", 0, 1)
                    pdf.ln(10)

                    # Tabela A Pagar
                    pdf.chapter_title("Proximos Vencimentos")
                    if not display_a.empty:
                        top_a_pdf = display_a.copy()
                        top_a_pdf['Valor'] = top_a_pdf['Valor'].apply(formatar_moeda_br)
                        pdf.create_table(top_a_pdf)
                    else:
                        pdf.set_font("Arial", "", 10)
                        pdf.cell(0, 10, "Sem dados neste periodo.", 0, 1)

                    # Output
                    pdf_bytes = pdf.output(dest='S').encode('latin-1')
                    st.download_button("⬇️ Clique para Download do PDF", data=pdf_bytes, file_name="Relatorio_Financeiro.pdf", mime='application/pdf')

                    if logo_temp_path: os.remove(logo_temp_path)

                except Exception as e:
                    st.error(f"Erro ao gerar PDF: {e}")

        with tab_wpp:
            # Texto inteligente
            maior_fornecedor = top_p.iloc[0][data['cols_p']['desc']] if not top_p.empty else "N/A"
            msg = f"""*Relatório de Pagamentos* 📊
Período: {data['periodo_txt']}

✅ *PAGO (Semana Passada)*
Total: {formatar_moeda_br(total_pago)}
Maior fornecedor: {maior_fornecedor}

📅 *A PAGAR (Esta Semana)*
Total: {formatar_moeda_br(total_apagar)}
Boletos a vencer: {len(data['apagar'])}

📄 *PDF detalhado disponível.*"""
            st.text_area("Copiar Mensagem:", value=msg, height=250)

else:
    st.info("👋 Para começar, faça o upload dos arquivos 'Contas Pagas' e 'A Pagar' na barra lateral.")