# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdYc7Fxsa_45G724edQkd-65zKIkiHdh
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime
import tempfile
import os
from fpdf import FPDF

# --- CONFIGURAÇÃO INICIAL ---
st.set_page_config(
    page_title="Controle de Pagamentos",
    page_icon="💲",
    layout="wide"
)

# --- ESTILOS CSS (Refinado) ---
st.markdown("""
    <style>
    .report-container {
        background-color: white;
        padding: 2rem;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        border: 1px solid #f0f0f0;
    }
    .kpi-card {
        background-color: #f8f9fa;
        border-radius: 8px;
        padding: 15px;
        border-left: 5px solid #3b82f6;
        height: 100%;
    }
    .big-number { font-size: 22px; font-weight: bold; color: #1f2937; margin-top: 5px; }
    .small-label { font-size: 13px; color: #6b7280; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
    </style>
""", unsafe_allow_html=True)

# --- FUNÇÕES DE UTILIDADE ---
def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def limpar_valor_moeda(valor):
    if isinstance(valor, (int, float)): return abs(float(valor))
    if isinstance(valor, str):
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: return abs(float(limpo))
        except: return 0.0
    return 0.0

def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith(('.xlsx', '.xls')):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except: return None

def selecionar_coluna(df, label, key_suffix, keywords):
    """Tenta adivinhar a coluna, mas permite troca manual"""
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break

    key = f"sel_{key_suffix}"
    if key not in st.session_state:
        st.session_state[key] = cols[default_idx] if cols else None

    selected = st.selectbox(f"{label}", cols, index=default_idx, key=key)
    return selected

# --- CLASSE PDF PROFISSIONAL ---
class PDFProfissional(FPDF):
    def __init__(self, logo_path=None, periodo=""):
        super().__init__()
        self.logo_path = logo_path
        self.periodo = periodo

    def header(self):
        self.set_fill_color(245, 247, 250)
        self.rect(0, 0, 210, 40, 'F')

        if self.logo_path:
            try:
                self.image(self.logo_path, 10, 8, 30)
            except: pass

        self.set_font('Arial', 'B', 18)
        self.set_xy(50, 10)
        self.cell(0, 10, 'Relatorio de Contas Pagas e A Pagar', 0, 1, 'L')

        self.set_font('Arial', '', 10)
        self.set_text_color(100, 100, 100)
        self.set_xy(50, 20)
        self.cell(0, 10, f'Periodo Geral: {self.periodo}', 0, 1, 'L')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Pagina {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(31, 41, 55)
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_draw_color(59, 130, 246)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def kpi_card(self, label, value, x, y):
        self.set_xy(x, y)
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(220, 220, 220)
        self.rect(x, y, 60, 25, 'FD')

        self.set_xy(x + 2, y + 4)
        self.set_font('Arial', '', 8)
        self.set_text_color(100)
        # Quebra texto do label se for longo (gambiarra simples)
        if len(label) > 25:
             parts = label.split(' ', 2)
             self.cell(56, 4, f"{parts[0]} {parts[1]}", 0, 1, 'C')
             self.set_xy(x + 2, y + 8)
             self.cell(56, 4, parts[2] if len(parts)>2 else "", 0, 1, 'C')
        else:
             self.cell(56, 5, label, 0, 1, 'C')

        self.set_xy(x + 2, y + 13)
        self.set_font('Arial', 'B', 12)
        self.set_text_color(0)
        self.cell(56, 8, value, 0, 1, 'C')

    def create_table(self, df):
        # Header Tabela
        self.set_font('Arial', 'B', 10)
        self.set_fill_color(59, 130, 246)
        self.set_text_color(255)

        # Larguras ajustadas: Data (Pequena), Fornecedor (Grande), Valor (Médio)
        col_widths = [30, 115, 45]
        headers = ["Data", "Fornecedor / Descricao", "Valor (R$)"]

        for i, h in enumerate(headers):
            self.cell(col_widths[i], 8, str(h), 1, 0, 'C', 1)
        self.ln()

        # Linhas
        self.set_font('Arial', '', 9)
        self.set_text_color(0)
        fill = False

        total = 0

        for _, row in df.iterrows():
            self.set_fill_color(240, 245, 255) if fill else self.set_fill_color(255)

            # Coluna 0: Data
            txt_data = str(row[0])

            # Coluna 1: Fornecedor (Corta se for muito grande para não quebrar layout)
            txt_forn = str(row[1])[:55]
            try: txt_forn = txt_forn.encode('latin-1', 'replace').decode('latin-1')
            except: pass

            # Coluna 2: Valor
            txt_val = str(row[2])

            self.cell(col_widths[0], 7, txt_data, 1, 0, 'C', fill)
            self.cell(col_widths[1], 7, txt_forn, 1, 0, 'L', fill)
            self.cell(col_widths[2], 7, txt_val, 1, 1, 'R', fill)
            fill = not fill

            # Soma simples para garantir que temos o valor numérico tratado no df original
            # (Aqui assumimos que a coluna 3 oculta ou o dado original tinha o float)
            # Para simplificar o PDF, não recalculamos soma aqui, confiamos nos KPIs.

# --- INTERFACE E LÓGICA ---

# Sidebar - Controle Principal
with st.sidebar:
    st.header("1. Arquivos")
    uploaded_logo = st.file_uploader("Logo da Empresa (Opcional)", type=['png', 'jpg'])
    uploaded_pagas = st.file_uploader("Relatório: PAGAS", type=['csv', 'xlsx'])
    uploaded_apagar = st.file_uploader("Relatório: A PAGAR", type=['csv', 'xlsx'])

    st.divider()
    mode_apresentacao = st.toggle("📺 Modo Apresentação", value=False)

# VARIÁVEIS DE ESTADO
if 'processed_data' not in st.session_state:
    st.session_state.processed_data = None

# --- PROCESSAMENTO DOS DADOS ---
if not mode_apresentacao and uploaded_pagas and uploaded_apagar:

    with st.sidebar.expander("⚙️ Configurar Colunas", expanded=False):
        st.markdown("**1. Contas Pagas**")
        df_pagas = carregar_dados(uploaded_pagas)
        if df_pagas is not None:
            col_p_data = selecionar_coluna(df_pagas, "Data Pagamento", "p_data", ['data', 'pagamento'])
            col_p_val = selecionar_coluna(df_pagas, "Valor", "p_val", ['valor', 'pago', 'total'])
            col_p_desc = selecionar_coluna(df_pagas, "Fornecedor", "p_desc", ['fornecedor', 'nome', 'descrição'])
            col_p_cat = selecionar_coluna(df_pagas, "Categoria (Opcional)", "p_cat", ['categoria', 'classificação'])

        st.divider()
        st.markdown("**2. Contas a Pagar**")
        df_apagar = carregar_dados(uploaded_apagar)
        if df_apagar is not None:
            col_a_data = selecionar_coluna(df_apagar, "Data Vencimento", "a_data", ['vencimento', 'data'])
            col_a_val = selecionar_coluna(df_apagar, "Valor", "a_val", ['valor', 'líquido', 'aberto'])
            col_a_desc = selecionar_coluna(df_apagar, "Fornecedor", "a_desc", ['fornecedor', 'nome', 'descrição'])

    if df_pagas is not None and df_apagar is not None:
        try:
            # Tratamento Pagas
            df_pagas[col_p_data] = pd.to_datetime(df_pagas[col_p_data], dayfirst=True, errors='coerce')
            df_pagas['valor_final'] = df_pagas[col_p_val].apply(limpar_valor_moeda)
            df_pagas = df_pagas.dropna(subset=[col_p_data])

            if not df_pagas.empty:
                min_pagas = df_pagas[col_p_data].min()
                max_pagas = df_pagas[col_p_data].max()
                str_periodo_pagas = f"{min_pagas.strftime('%d/%m')} a {max_pagas.strftime('%d/%m')}"
            else:
                str_periodo_pagas = "N/A"

            # Tratamento A Pagar
            df_apagar[col_a_data] = pd.to_datetime(df_apagar[col_a_data], dayfirst=True, errors='coerce')
            df_apagar['valor_final'] = df_apagar[col_a_val].apply(limpar_valor_moeda)
            df_apagar = df_apagar.dropna(subset=[col_a_data])

            if not df_apagar.empty:
                min_apagar = df_apagar[col_a_data].min()
                max_apagar = df_apagar[col_a_data].max()
                str_periodo_apagar = f"{min_apagar.strftime('%d/%m')} a {max_apagar.strftime('%d/%m')}"
            else:
                str_periodo_apagar = "N/A"

            st.session_state.processed_data = {
                'pagas': df_pagas,
                'apagar': df_apagar,
                'cols_p': {'data': col_p_data, 'val': 'valor_final', 'desc': col_p_desc, 'cat': col_p_cat},
                'cols_a': {'data': col_a_data, 'val': 'valor_final', 'desc': col_a_desc},
                'periodo_txt': f"{str_periodo_pagas} e {str_periodo_apagar}",
                'dates': {'p_str': str_periodo_pagas, 'a_str': str_periodo_apagar},
                'totals': {
                    'pago': df_pagas['valor_final'].sum(),
                    'apagar': df_apagar['valor_final'].sum()
                }
            }
        except Exception as e:
            st.error(f"Erro ao processar dados. Detalhe: {e}")

# --- RENDERIZAÇÃO ---

data = st.session_state.processed_data

if data:
    df_p = data['pagas'].copy()
    if not mode_apresentacao and data['cols_p']['cat'] in df_p.columns:
        st.sidebar.divider()
        st.sidebar.markdown("🔎 **Filtros**")
        cats = sorted(list(df_p[data['cols_p']['cat']].astype(str).unique()))
        sel_cat = st.sidebar.multiselect("Filtrar Categoria", cats)
        if sel_cat:
            df_p = df_p[df_p[data['cols_p']['cat']].astype(str).isin(sel_cat)]

    total_pago = df_p['valor_final'].sum()
    total_apagar = data['totals']['apagar']

    with st.container():
        if mode_apresentacao:
            st.markdown("### 📺 Modo Apresentação")
            st.markdown(f"# Resultados Financeiros")
            st.markdown(f"*{data['periodo_txt']}*")
        else:
            st.markdown(f"## 📑 Controle de Pagamentos Semanal")
            st.markdown(f"**Período:** {data['periodo_txt']}")

        st.markdown("---")

        # 1. KPIs Cards com TEXTOS CORRIGIDOS
        k1, k2, k3 = st.columns(3)
        diff = total_apagar - total_pago

        # Rótulos descritivos solicitados
        label_pago = f"CONTAS PAGAS ({data['dates']['p_str']})"
        label_apagar = f"CONTAS A PAGAR ({data['dates']['a_str']})"
        label_var = "VARIAÇÃO DE FLUXO (Semana x Semana)"

        with k1:
            st.markdown(f"""
            <div class="kpi-card">
                <div class="small-label">{label_pago}</div>
                <div class="big-number" style="color:#10b981">{formatar_moeda_br(total_pago)}</div>
            </div>""", unsafe_allow_html=True)

        with k2:
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: #f59e0b;">
                <div class="small-label">{label_apagar}</div>
                <div class="big-number" style="color:#d97706">{formatar_moeda_br(total_apagar)}</div>
            </div>""", unsafe_allow_html=True)

        with k3:
            lbl_diff_extra = " (Aumento)" if diff > 0 else " (Redução)"
            cor_diff = "#ef4444" if diff > 0 else "#10b981"
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: {cor_diff};">
                <div class="small-label">{label_var}</div>
                <div class="big-number" style="color:{cor_diff}">{formatar_moeda_br(abs(diff))} <span style="font-size:16px">{lbl_diff_extra}</span></div>
            </div>""", unsafe_allow_html=True)

        st.write("")

        # 2. Gráficos
        g1, g2 = st.columns(2)
        with g1:
            st.subheader("Evolução Pagamentos")
            if not df_p.empty:
                chart_p = alt.Chart(df_p).mark_bar(color='#10b981', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_p']['data'], axis=alt.Axis(format='%d/%m', title='Data')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_p']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_p, use_container_width=True)

        with g2:
            st.subheader("Previsão de Saídas")
            if not data['apagar'].empty:
                chart_a = alt.Chart(data['apagar']).mark_bar(color='#f59e0b', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_a']['data'], axis=alt.Axis(format='%d/%m', title='Vencimento')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_a']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_a, use_container_width=True)

    # --- ÁREA EXCLUSIVA: PDF E WHATSAPP ---
    if not mode_apresentacao:
        st.divider()
        st.subheader("📤 Exportação e Envio")

        tab_pdf, tab_wpp = st.tabs(["📄 Gerar PDF Completo", "📱 Texto WhatsApp"])

        with tab_pdf:
            st.write("Relatório completo com todas as contas listadas.")
            if st.button("Baixar Relatório em PDF"):
                try:
                    logo_temp_path = None
                    if uploaded_logo:
                        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                            tmp.write(uploaded_logo.getvalue())
                            logo_temp_path = tmp.name

                    pdf = PDFProfissional(logo_temp_path, data['periodo_txt'])
                    pdf.add_page()

                    # KPIs no PDF
                    pdf.kpi_card("TOTAL PAGO (Periodo 1)", formatar_moeda_br(total_pago), 10, 50)
                    pdf.kpi_card("A PAGAR (Periodo 2)", formatar_moeda_br(total_apagar), 75, 50)
                    pdf.kpi_card("VARIACAO DE FLUXO", formatar_moeda_br(abs(diff)), 140, 50)
                    pdf.ln(40)

                    # Tabela 1: TODAS as Contas Pagas (Ordenadas por data)
                    pdf.chapter_title("Relatorio Detalhado: Contas Pagas")
                    if not df_p.empty:
                        # Prepara dados: Data | Fornecedor | Valor
                        full_p = df_p.sort_values(by=data['cols_p']['data']).copy()
                        full_p_pdf = pd.DataFrame()
                        full_p_pdf['Data'] = full_p[data['cols_p']['data']].dt.strftime('%d/%m')
                        full_p_pdf['Fornecedor'] = full_p[data['cols_p']['desc']]
                        full_p_pdf['Valor'] = full_p['valor_final'].apply(formatar_moeda_br)

                        pdf.create_table(full_p_pdf)
                    else:
                        pdf.set_font("Arial", "", 10)
                        pdf.cell(0, 10, "Sem dados neste periodo.", 0, 1)
                    pdf.ln(10)

                    # Tabela 2: TODAS as Contas a Pagar (Ordenadas por data)
                    pdf.chapter_title("Relatorio Detalhado: Contas a Pagar")
                    if not data['apagar'].empty:
                        full_a = data['apagar'].sort_values(by=data['cols_a']['data']).copy()
                        full_a_pdf = pd.DataFrame()
                        full_a_pdf['Data'] = full_a[data['cols_a']['data']].dt.strftime('%d/%m')
                        full_a_pdf['Fornecedor'] = full_a[data['cols_a']['desc']]
                        full_a_pdf['Valor'] = full_a['valor_final'].apply(formatar_moeda_br)

                        pdf.create_table(full_a_pdf)
                    else:
                        pdf.set_font("Arial", "", 10)
                        pdf.cell(0, 10, "Sem dados neste periodo.", 0, 1)

                    pdf_bytes = pdf.output(dest='S').encode('latin-1')
                    st.download_button("⬇️ Baixar PDF", data=pdf_bytes, file_name="Relatorio_Financeiro.pdf", mime='application/pdf')

                    if logo_temp_path: os.remove(logo_temp_path)

                except Exception as e:
                    st.error(f"Erro ao gerar PDF: {e}")

        with tab_wpp:
            # Texto inteligente
            maior_fornecedor = df_p.nlargest(1, 'valor_final')[data['cols_p']['desc']].iloc[0] if not df_p.empty else "N/A"
            msg = f"""*Relatório de Pagamentos* 📊
Período: {data['periodo_txt']}

✅ *PAGO ({data['dates']['p_str']})*
Total: {formatar_moeda_br(total_pago)}
Maior fornecedor: {maior_fornecedor}

📅 *A PAGAR ({data['dates']['a_str']})*
Total: {formatar_moeda_br(total_apagar)}
Boletos a vencer: {len(data['apagar'])}"""

            st.markdown("##### Mensagem Pronta:")
            # st.code gera um bloco de código que tem botão de copiar nativo no canto superior direito
            st.code(msg, language="markdown")

else:
    st.info("👋 Para começar, faça o upload dos arquivos 'Contas Pagas' e 'A Pagar' na barra lateral.")