# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15caiMCL8UFBpWpnsPtCFZxGl81oeLJRg
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime, timedelta

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(
    page_title="Relatório Financeiro Semanal",
    page_icon="📈",
    layout="centered" # Layout centralizado fica melhor para prints de celular
)

# --- ESTILOS CSS (Visual Premium) ---
st.markdown("""
    <style>
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; border: 1px solid #e0e0e0; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    .report-card { background-color: white; padding: 20px; border-radius: 15px; border: 1px solid #ddd; margin-bottom: 20px; }
    h3 { color: #333; }
    </style>
    """, unsafe_allow_html=True)

# --- FUNÇÕES AUXILIARES ---
def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith('.xlsx') or uploaded_file.name.endswith('.xls'):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except Exception as e:
        st.error(f"Erro ao ler arquivo: {e}")
        return None

def limpar_valor_moeda(valor):
    if isinstance(valor, (int, float)): return valor
    if isinstance(valor, str):
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: return float(limpo)
        except: return 0.0
    return 0.0

def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def selecionar_coluna(df, label, key_suffix, keywords):
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break
    return st.selectbox(f"Coluna de **{label}**:", cols, index=default_idx, key=f"sel_{key_suffix}")

def criar_grafico_barras(df, x_col, y_col, cor, tooltip_col):
    """Gera um gráfico de barras limpo usando Altair"""
    chart = alt.Chart(df).mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3).encode(
        x=alt.X(x_col, axis=alt.Axis(format='%d/%m', title='Data', labelAngle=0)),
        y=alt.Y(y_col, axis=alt.Axis(title='Valor (R$)')),
        color=alt.value(cor),
        tooltip=[alt.Tooltip(x_col, format='%d/%m/%Y'), tooltip_col, alt.Tooltip(y_col, format=',.2f')]
    ).properties(height=200)
    return chart

# --- INTERFACE PRINCIPAL ---
st.title("📈 Gerador de Relatório")
st.markdown("Suba os arquivos do Nibo para gerar o texto e os gráficos.")

# DATAS E ARQUIVOS
with st.expander("📂 Configuração e Arquivos", expanded=True):
    col_d, col_u = st.columns([1, 2])
    with col_d:
        data_ref = st.date_input("Data Referência", datetime.now())

    # Cálculo de datas
    inicio_semana_atual = data_ref - timedelta(days=data_ref.weekday())
    fim_semana_atual = inicio_semana_atual + timedelta(days=6)
    inicio_semana_passada = inicio_semana_atual - timedelta(days=7)
    fim_semana_passada = inicio_semana_atual - timedelta(days=1)

    str_passada = f"{inicio_semana_passada.strftime('%d/%m')} a {fim_semana_passada.strftime('%d/%m')}"
    str_atual = f"{inicio_semana_atual.strftime('%d/%m')} a {fim_semana_atual.strftime('%d/%m')}"

    with col_u:
        arquivo_pagas = st.file_uploader("Contas PAGAS (Semana Passada)", type=['csv', 'xlsx'])
        arquivo_apagar = st.file_uploader("Contas A PAGAR (Esta Semana)", type=['csv', 'xlsx'])

# VARIÁVEIS GLOBAIS
total_pago = 0.0
total_a_pagar = 0.0
df_pagas_final = pd.DataFrame()
df_apagar_final = pd.DataFrame()

# --- PROCESSAMENTO ---
if arquivo_pagas and arquivo_apagar:

    # 1. PROCESSAR PAGAS
    df_pagas = carregar_dados(arquivo_pagas)
    if df_pagas is not None:
        st.sidebar.markdown("### Configuração Pagas")
        col_data_p = selecionar_coluna(df_pagas, "Data Pagamento", "pagas_data", ['pagamento', 'baixa', 'data'])
        col_val_p = selecionar_coluna(df_pagas, "Valor", "pagas_valor", ['valor pago', 'valor', 'total'])
        col_desc_p = selecionar_coluna(df_pagas, "Descrição", "pagas_desc", ['fornecedor', 'descrição', 'nome'])

        df_pagas[col_data_p] = pd.to_datetime(df_pagas[col_data_p], dayfirst=True, errors='coerce')
        df_pagas['valor_tratado'] = df_pagas[col_val_p].apply(limpar_valor_moeda)
        mask_p = (df_pagas[col_data_p].dt.date >= inicio_semana_passada) & (df_pagas[col_data_p].dt.date <= fim_semana_passada)
        df_pagas_final = df_pagas[mask_p].copy()
        total_pago = df_pagas_final['valor_tratado'].sum()

    # 2. PROCESSAR A PAGAR
    df_apagar = carregar_dados(arquivo_apagar)
    if df_apagar is not None:
        st.sidebar.markdown("### Configuração A Pagar")
        col_data_a = selecionar_coluna(df_apagar, "Data Vencimento", "apagar_data", ['vencimento', 'data'])
        col_val_a = selecionar_coluna(df_apagar, "Valor", "apagar_valor", ['valor líquido', 'valor', 'aberto'])
        col_desc_a = selecionar_coluna(df_apagar, "Descrição", "apagar_desc", ['fornecedor', 'descrição', 'nome'])

        df_apagar[col_data_a] = pd.to_datetime(df_apagar[col_data_a], dayfirst=True, errors='coerce')
        df_apagar['valor_tratado'] = df_apagar[col_val_a].apply(limpar_valor_moeda)
        mask_a = (df_apagar[col_data_a].dt.date >= inicio_semana_atual) & (df_apagar[col_data_a].dt.date <= fim_semana_atual)
        df_apagar_final = df_apagar[mask_a].copy()
        total_a_pagar = df_apagar_final['valor_tratado'].sum()

    st.divider()

    # --- ÁREA VISUAL (CARTÃO PARA PRINT) ---
    st.subheader("📸 Cartão para Print (Visual)")
    st.info("Dica: Tire um print da área abaixo para enviar como imagem.")

    container_print = st.container()
    with container_print:
        # Cabeçalho do Cartão
        kpi1, kpi2 = st.columns(2)
        kpi1.metric(f"Pago ({str_passada})", formatar_moeda_br(total_pago), delta="Realizado", delta_color="normal")
        kpi2.metric(f"A Pagar ({str_atual})", formatar_moeda_br(total_a_pagar), delta="Previsão", delta_color="inverse")

        st.markdown("---")

        # Gráficos Lado a Lado
        g1, g2 = st.columns(2)

        with g1:
            st.markdown(f"**Saídas por Dia** ({str_passada})")
            if not df_pagas_final.empty:
                # Agrupa por dia para o gráfico
                chart_data_p = df_pagas_final.groupby(col_data_p)['valor_tratado'].sum().reset_index()
                grafico_p = criar_grafico_barras(chart_data_p, col_data_p, 'valor_tratado', '#28a745', col_data_p)
                st.altair_chart(grafico_p, use_container_width=True)
            else:
                st.caption("Sem dados.")

        with g2:
            st.markdown(f"**Vencimentos** ({str_atual})")
            if not df_apagar_final.empty:
                # Agrupa por dia para o gráfico
                chart_data_a = df_apagar_final.groupby(col_data_a)['valor_tratado'].sum().reset_index()
                grafico_a = criar_grafico_barras(chart_data_a, col_data_a, 'valor_tratado', '#ffc107', col_data_a)
                st.altair_chart(grafico_a, use_container_width=True)
            else:
                st.caption("Sem dados.")

    st.divider()

    # --- ÁREA DE TEXTO (WHATSAPP) ---
    st.subheader("📲 Texto para Copiar")

    # Prepara lista top 3
    top_3 = df_pagas_final.nlargest(3, 'valor_tratado')
    lista_pagas = ""
    for _, row in top_3.iterrows():
        lista_pagas += f"▫️ {row[col_desc_p]}: {formatar_moeda_br(row['valor_tratado'])}\n"
    if lista_pagas == "": lista_pagas = "▫️ Sem destaques.\n"

    mensagem = f"""Bom dia! ☀️
Resumo Financeiro Semanal

✅ *REALIZADO ({str_passada})*
Total Pago: *{formatar_moeda_br(total_pago)}*
Principais saídas:
{lista_pagas}
📅 *PREVISÃO ({str_atual})*
Total a Vencer: *{formatar_moeda_br(total_a_pagar)}*
Qtd. boletos: {len(df_apagar_final)}

📎 *Segue em anexo o relatório detalhado.*
Qualquer dúvida, estou à disposição!"""

    st.text_area("Copiar e colar:", value=mensagem, height=300)

else:
    st.info("👈 Por favor, faça o upload dos dois arquivos (Pagas e A Pagar) na barra lateral ou acima.")