# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yuA9mvvNCfevEMcFtVvQS4YkGptOgcFR
"""

import streamlit as st
import pandas as pd
from datetime import datetime, timedelta

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(
    page_title="Gerador de Relatório Semanal",
    page_icon="📊",
    layout="centered"
)

# --- ESTILIZAÇÃO CSS (Para dar o ar 'Premium') ---
st.markdown("""
    <style>
    .big-font { font-size:20px !important; font-weight: bold; }
    .stMetric { background-color: #f0f2f6; padding: 10px; border-radius: 10px; }
    div[data-testid="stExpander"] div[role="button"] p { font-size: 1.1rem; font-weight: 600; }
    </style>
    """, unsafe_allow_html=True)

# --- FUNÇÕES AUXILIARES ---
def carregar_dados(uploaded_file):
    try:
        # Tenta ler como Excel primeiro, se falhar, tenta CSV
        if uploaded_file.name.endswith('.xlsx') or uploaded_file.name.endswith('.xls'):
            df = pd.read_excel(uploaded_file)
        else:
            # Tenta separadores comuns de CSV brasileiro
            try:
                df = pd.read_csv(uploaded_file, sep=',')
            except:
                df = pd.read_csv(uploaded_file, sep=';')
        return df
    except Exception as e:
        st.error(f"Erro ao ler arquivo: {e}")
        return None

def formatar_moeda(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

# --- INTERFACE PRINCIPAL ---
st.title("📊 Relatório Executivo Semanal")
st.markdown("Gere o briefing financeiro para seus clientes em segundos.")

# 1. Upload e Configuração
with st.sidebar:
    st.header("📂 Dados de Entrada")
    arquivo = st.file_uploader("Arraste o relatório do Nibo aqui (Excel/CSV)", type=['csv', 'xlsx', 'xls'])

    st.divider()

    st.header("⚙️ Configuração de Datas")
    # Define a data de referência (padrão é hoje)
    data_ref = st.date_input("Data de Referência (Hoje)", datetime.now())

    # Lógica de datas (Semana Passada vs Atual)
    # Segunda-feira da semana atual
    inicio_semana_atual = data_ref - timedelta(days=data_ref.weekday())
    fim_semana_atual = inicio_semana_atual + timedelta(days=6)

    inicio_semana_passada = inicio_semana_atual - timedelta(days=7)
    fim_semana_passada = inicio_semana_atual - timedelta(days=1)

    st.info(f"**Semana Passada:** {inicio_semana_passada.strftime('%d/%m')} a {fim_semana_passada.strftime('%d/%m')}")
    st.info(f"**Semana Atual:** {inicio_semana_atual.strftime('%d/%m')} a {fim_semana_atual.strftime('%d/%m')}")

# 2. Processamento
if arquivo:
    df = carregar_dados(arquivo)

    if df is not None:
        # --- NORMALIZAÇÃO DE COLUNAS (Tenta adivinhar os nomes comuns do Nibo) ---
        # Ajuste aqui se as colunas do seu Nibo vierem com nomes muito diferentes
        colunas_map = {
            'Data de Vencimento': 'data_vencimento',
            'Vencimento': 'data_vencimento',
            'Data Pagamento': 'data_pagamento',
            'Pagamento': 'data_pagamento',
            'Data': 'data_generica',
            'Valor': 'valor',
            'Valor Pago': 'valor_pago',
            'Valor Líquido': 'valor',
            'Fornecedor': 'descricao',
            'Descrição': 'descricao',
            'Cliente': 'descricao',
            'Status': 'status'
        }

        # Normaliza nomes de colunas para minúsculo para facilitar o match
        df.columns = [c.strip() for c in df.columns]
        df_cols_lower = {c.lower(): c for c in df.columns}

        # Seleciona as colunas críticas
        col_data_pag = next((df_cols_lower[c] for c in ['data pagamento', 'pagamento', 'data baixa'] if c in df_cols_lower), None)
        col_data_venc = next((df_cols_lower[c] for c in ['data de vencimento', 'vencimento', 'data'] if c in df_cols_lower), None)
        col_valor = next((df_cols_lower[c] for c in ['valor', 'valor pago', 'valor líquido'] if c in df_cols_lower), None)
        col_desc = next((df_cols_lower[c] for c in ['fornecedor', 'descrição', 'cliente', 'histórico'] if c in df_cols_lower), None)

        if not (col_data_venc and col_valor and col_desc):
            st.error("Não consegui identificar automaticamente as colunas de Data, Valor e Descrição. Verifique o arquivo.")
        else:
            # Converte datas
            if col_data_pag:
                df[col_data_pag] = pd.to_datetime(df[col_data_pag], dayfirst=True, errors='coerce')
            df[col_data_venc] = pd.to_datetime(df[col_data_venc], dayfirst=True, errors='coerce')

            # FILTROS
            # 1. Realizado (Semana Passada) - Baseado em data de pagamento se existir, senão data genérica
            col_data_realizado = col_data_pag if col_data_pag else col_data_venc

            mask_realizado = (df[col_data_realizado].dt.date >= inicio_semana_passada) & \
                             (df[col_data_realizado].dt.date <= fim_semana_passada)
            # Se tiver coluna status, filtra por pagos, senão assume tudo nessa data
            if 'status' in [c.lower() for c in df.columns]:
                 col_status = next(df_cols_lower[c] for c in ['status'] if c in df_cols_lower)
                 mask_realizado = mask_realizado & (df[col_status].astype(str).str.contains('Pago|Baixado', case=False, na=False))

            df_realizado = df[mask_realizado].copy()

            # 2. Previsto (Semana Atual)
            mask_previsto = (df[col_data_venc].dt.date >= inicio_semana_atual) & \
                            (df[col_data_venc].dt.date <= fim_semana_atual)

            if 'status' in [c.lower() for c in df.columns]:
                 col_status = next(df_cols_lower[c] for c in ['status'] if c in df_cols_lower)
                 mask_previsto = mask_previsto & (df[col_status].astype(str).str.contains('Aberto|Agendado|Pendente', case=False, na=False))

            df_previsto = df[mask_previsto].copy()

            # TOTAIS
            total_pago = df_realizado[col_valor].sum()
            total_a_pagar = df_previsto[col_valor].sum()

            # --- DASHBOARD VISUAL ---
            st.divider()
            c1, c2 = st.columns(2)
            with c1:
                st.metric("Total Pago (Semana Passada)", formatar_moeda(total_pago), delta="Realizado", delta_color="normal")
            with c2:
                st.metric("A Pagar (Esta Semana)", formatar_moeda(total_a_pagar), delta="Previsão", delta_color="inverse")

            # --- GERADOR DE TEXTO DO WHATSAPP ---
            st.subheader("📱 Texto para Copiar")

            # Top 3 gastos para o resumo
            top_gastos = df_realizado.nlargest(3, col_valor)
            lista_top_gastos = ""
            if not top_gastos.empty:
                for _, row in top_gastos.iterrows():
                    lista_top_gastos += f"▫️ {row[col_desc]}: {formatar_moeda(row[col_valor])}\n"
            else:
                lista_top_gastos = "▫️ Sem pagamentos relevantes.\n"

            # Montagem da mensagem
            mensagem_whatsapp = f"""Bom dia! ☀️
Segue o resumo financeiro semanal.

✅ *REALIZADO (Semana Passada)*
Total Pago: *{formatar_moeda(total_pago)}*
Principais saídas:
{lista_top_gastos}
📅 *PREVISÃO (Esta Semana)*
Total a Vencer: *{formatar_moeda(total_a_pagar)}*
Qtd. boletos: {len(df_previsto)}

📎 *Segue em anexo o relatório detalhado.*
Dúvidas estou à disposição!"""

            st.text_area("Copie o texto abaixo:", value=mensagem_whatsapp, height=300)

            # --- DETALHAMENTO (TABELAS) ---
            with st.expander("🔍 Ver Detalhes (Tabelas)"):
                st.subheader("Pagamentos Realizados")
                if not df_realizado.empty:
                    st.dataframe(df_realizado[[col_data_realizado, col_desc, col_valor]].sort_values(by=col_data_realizado), hide_index=True, use_container_width=True)
                else:
                    st.info("Nenhum pagamento encontrado no período.")

                st.subheader("Contas a Pagar")
                if not df_previsto.empty:
                    st.dataframe(df_previsto[[col_data_venc, col_desc, col_valor]].sort_values(by=col_data_venc), hide_index=True, use_container_width=True)
                else:
                    st.success("Nenhuma conta a vencer nesta semana!")

else:
    # Tela inicial de boas-vindas
    st.info("👈 Faça o upload do arquivo Excel ou CSV do Nibo na barra lateral para começar.")
    st.markdown("---")
    st.markdown("**Dica:** No Nibo, vá em Contas a Pagar > Exportar Relatório e use esse arquivo aqui.")