# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zKpN4PrxGsT6PN37vWGH2ykEPCt2guH9
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime
import tempfile
import os
from fpdf import FPDF

# --- CONFIGURAÇÃO INICIAL ---
st.set_page_config(
    page_title="Controle de Pagamentos",
    page_icon="💲",
    layout="wide"
)

# --- ESTILOS CSS ---
st.markdown("""
    <style>
    .report-container {
        background-color: white;
        padding: 2rem;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        border: 1px solid #f0f0f0;
    }
    .kpi-card {
        background-color: #f8f9fa;
        border-radius: 8px;
        padding: 15px;
        border-left: 5px solid #3b82f6;
        height: 100%;
    }
    .big-number { font-size: 22px; font-weight: bold; color: #1f2937; margin-top: 5px; }
    .small-label { font-size: 13px; color: #6b7280; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
    </style>
""", unsafe_allow_html=True)

# --- FUNÇÕES DE UTILIDADE ---
def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def limpar_valor_moeda(valor):
    if isinstance(valor, (int, float)): return abs(float(valor))
    if isinstance(valor, str):
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: return abs(float(limpo))
        except: return 0.0
    return 0.0

def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith(('.xlsx', '.xls')):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except: return None

def selecionar_coluna(df, label, key_suffix, keywords):
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break

    key = f"sel_{key_suffix}"
    if key not in st.session_state:
        st.session_state[key] = cols[default_idx] if cols else None

    selected = st.selectbox(f"{label}", cols, index=default_idx, key=key)
    return selected

# --- CLASSE PDF PROFISSIONAL (ATUALIZADA) ---
class PDFProfissional(FPDF):
    def __init__(self, logo_path=None, periodo="", titulo="Relatorio Financeiro"):
        super().__init__()
        self.logo_path = logo_path
        self.periodo = periodo
        self.titulo_relatorio = titulo

    def header(self):
        # Barra superior colorida
        self.set_fill_color(41, 98, 255) # Azul Royal
        self.rect(0, 0, 210, 5, 'F')

        self.ln(10)

        # Logo
        if self.logo_path:
            try:
                self.image(self.logo_path, 10, 15, 35)
            except: pass

        # Título
        self.set_font('Arial', 'B', 22)
        self.set_text_color(33, 33, 33)
        self.set_xy(50, 15)
        self.cell(0, 10, self.titulo_relatorio, 0, 1, 'L')

        # Subtítulo (Período)
        self.set_font('Arial', '', 11)
        self.set_text_color(100, 100, 100)
        self.set_xy(50, 25)
        self.cell(0, 10, f'{self.periodo}', 0, 1, 'L')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Pagina {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.ln(5)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(33, 33, 33)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 10, f"  {title}", 0, 1, 'L', 1)
        self.ln(4)

    def kpi_card(self, label, value, x, y):
        # Caixa Sombra
        self.set_fill_color(245, 245, 245)
        self.rect(x+1, y+1, 60, 25, 'F')
        # Caixa Principal
        self.set_fill_color(255, 255, 255)
        self.set_draw_color(200, 200, 200)
        self.rect(x, y, 60, 25, 'FD')

        # Label
        self.set_xy(x, y + 4)
        self.set_font('Arial', 'B', 8)
        self.set_text_color(100, 100, 100)
        self.cell(60, 5, label, 0, 1, 'C')

        # Value
        self.set_xy(x, y + 12)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(33, 33, 33)
        self.cell(60, 8, value, 0, 1, 'C')

    def create_table(self, df, include_cat=False):
        # Configuração das Colunas
        # Se tiver categoria: Data(25), Forn(85), Cat(45), Valor(35)
        # Se não tiver: Data(30), Forn(115), Valor(45)

        if include_cat:
            headers = ["Data", "Fornecedor", "Categoria", "Valor"]
            widths = [25, 85, 45, 35]
        else:
            headers = ["Data", "Fornecedor", "Valor"]
            widths = [30, 115, 45]

        # Header Tabela
        self.set_font('Arial', 'B', 10)
        self.set_fill_color(41, 98, 255) # Azul
        self.set_text_color(255)

        for i, h in enumerate(headers):
            self.cell(widths[i], 8, str(h), 1, 0, 'C', 1)
        self.ln()

        # Linhas
        self.set_font('Arial', '', 9)
        self.set_text_color(0)
        fill = False

        for _, row in df.iterrows():
            self.set_fill_color(245, 250, 255) if fill else self.set_fill_color(255)

            # Extração de dados
            dt = str(row[0])

            # Fornecedor (Truncar)
            forn = str(row[1])[:50]
            try: forn = forn.encode('latin-1', 'replace').decode('latin-1')
            except: pass

            if include_cat:
                # Categoria
                cat = str(row[2])[:25]
                try: cat = cat.encode('latin-1', 'replace').decode('latin-1')
                except: pass
                val = str(row[3])

                self.cell(widths[0], 7, dt, 1, 0, 'C', fill)
                self.cell(widths[1], 7, forn, 1, 0, 'L', fill)
                self.cell(widths[2], 7, cat, 1, 0, 'L', fill)
                self.cell(widths[3], 7, val, 1, 1, 'R', fill)
            else:
                val = str(row[2])
                self.cell(widths[0], 7, dt, 1, 0, 'C', fill)
                self.cell(widths[1], 7, forn, 1, 0, 'L', fill)
                self.cell(widths[2], 7, val, 1, 1, 'R', fill)

            fill = not fill

# --- INTERFACE E LÓGICA ---

# Sidebar - Controle Principal
with st.sidebar:
    st.header("1. Arquivos")
    uploaded_logo = st.file_uploader("Logo da Empresa (Opcional)", type=['png', 'jpg'])
    uploaded_pagas = st.file_uploader("Relatório: PAGAS", type=['csv', 'xlsx'])
    uploaded_apagar = st.file_uploader("Relatório: A PAGAR", type=['csv', 'xlsx'])

    st.divider()
    mode_apresentacao = st.toggle("📺 Modo Apresentação", value=False)

# VARIÁVEIS DE ESTADO
if 'processed_data' not in st.session_state:
    st.session_state.processed_data = None

# --- PROCESSAMENTO DOS DADOS ---
if not mode_apresentacao and uploaded_pagas and uploaded_apagar:

    with st.sidebar.expander("⚙️ Configurar Colunas", expanded=False):
        st.markdown("**1. Contas Pagas**")
        df_pagas = carregar_dados(uploaded_pagas)
        if df_pagas is not None:
            col_p_data = selecionar_coluna(df_pagas, "Data Pagamento", "p_data", ['data', 'pagamento'])
            col_p_val = selecionar_coluna(df_pagas, "Valor", "p_val", ['valor', 'pago', 'total'])
            col_p_desc = selecionar_coluna(df_pagas, "Fornecedor", "p_desc", ['fornecedor', 'nome', 'descrição'])
            col_p_cat = selecionar_coluna(df_pagas, "Categoria (Opcional)", "p_cat", ['categoria', 'classificação'])

        st.divider()
        st.markdown("**2. Contas a Pagar**")
        df_apagar = carregar_dados(uploaded_apagar)
        if df_apagar is not None:
            col_a_data = selecionar_coluna(df_apagar, "Data Vencimento", "a_data", ['vencimento', 'data'])
            col_a_val = selecionar_coluna(df_apagar, "Valor", "a_val", ['valor', 'líquido', 'aberto'])
            col_a_desc = selecionar_coluna(df_apagar, "Fornecedor", "a_desc", ['fornecedor', 'nome', 'descrição'])
            col_a_cat = selecionar_coluna(df_apagar, "Categoria (Opcional)", "a_cat", ['categoria', 'classificação'])

    if df_pagas is not None and df_apagar is not None:
        try:
            # Tratamento Pagas
            df_pagas[col_p_data] = pd.to_datetime(df_pagas[col_p_data], dayfirst=True, errors='coerce')
            df_pagas['valor_final'] = df_pagas[col_p_val].apply(limpar_valor_moeda)
            df_pagas = df_pagas.dropna(subset=[col_p_data])

            if not df_pagas.empty:
                min_pagas = df_pagas[col_p_data].min()
                max_pagas = df_pagas[col_p_data].max()
                str_periodo_pagas = f"{min_pagas.strftime('%d/%m')} a {max_pagas.strftime('%d/%m')}"
            else:
                str_periodo_pagas = "N/A"

            # Tratamento A Pagar
            df_apagar[col_a_data] = pd.to_datetime(df_apagar[col_a_data], dayfirst=True, errors='coerce')
            df_apagar['valor_final'] = df_apagar[col_a_val].apply(limpar_valor_moeda)
            df_apagar = df_apagar.dropna(subset=[col_a_data])

            if not df_apagar.empty:
                min_apagar = df_apagar[col_a_data].min()
                max_apagar = df_apagar[col_a_data].max()
                str_periodo_apagar = f"{min_apagar.strftime('%d/%m')} a {max_apagar.strftime('%d/%m')}"
            else:
                str_periodo_apagar = "N/A"

            st.session_state.processed_data = {
                'pagas': df_pagas,
                'apagar': df_apagar,
                'cols_p': {'data': col_p_data, 'val': 'valor_final', 'desc': col_p_desc, 'cat': col_p_cat},
                'cols_a': {'data': col_a_data, 'val': 'valor_final', 'desc': col_a_desc, 'cat': col_a_cat},
                'periodo_txt': f"{str_periodo_pagas} e {str_periodo_apagar}",
                'dates': {'p_str': str_periodo_pagas, 'a_str': str_periodo_apagar},
                'totals': {
                    'pago': df_pagas['valor_final'].sum(),
                    'apagar': df_apagar['valor_final'].sum()
                }
            }
        except Exception as e:
            st.error(f"Erro ao processar dados: {e}")

# --- RENDERIZAÇÃO ---

data = st.session_state.processed_data

if data:
    df_p = data['pagas'].copy()
    if not mode_apresentacao and data['cols_p']['cat'] in df_p.columns:
        st.sidebar.divider()
        st.sidebar.markdown("🔎 **Filtros**")
        cats = sorted(list(df_p[data['cols_p']['cat']].astype(str).unique()))
        sel_cat = st.sidebar.multiselect("Filtrar Categoria", cats)
        if sel_cat:
            df_p = df_p[df_p[data['cols_p']['cat']].astype(str).isin(sel_cat)]

    total_pago = df_p['valor_final'].sum()
    total_apagar = data['totals']['apagar']

    with st.container():
        if mode_apresentacao:
            st.markdown("### 📺 Modo Apresentação")
            st.markdown(f"# Resultados Financeiros")
            st.markdown(f"*{data['periodo_txt']}*")
        else:
            st.markdown(f"## 📑 Controle de Pagamentos Semanal")
            st.markdown(f"**Período de Análise:** {data['periodo_txt']}")

        st.markdown("---")

        # 1. KPIs
        k1, k2, k3 = st.columns(3)
        diff = total_apagar - total_pago

        with k1:
            st.markdown(f"""
            <div class="kpi-card">
                <div class="small-label">TOTAL PAGO ({data['dates']['p_str']})</div>
                <div class="big-number" style="color:#10b981">{formatar_moeda_br(total_pago)}</div>
            </div>""", unsafe_allow_html=True)

        with k2:
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: #f59e0b;">
                <div class="small-label">A PAGAR ({data['dates']['a_str']})</div>
                <div class="big-number" style="color:#d97706">{formatar_moeda_br(total_apagar)}</div>
            </div>""", unsafe_allow_html=True)

        with k3:
            lbl_diff = "AUMENTO DE FLUXO" if diff > 0 else "REDUÇÃO DE FLUXO"
            cor_diff = "#ef4444" if diff > 0 else "#10b981"
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: {cor_diff};">
                <div class="small-label">{lbl_diff}</div>
                <div class="big-number" style="color:{cor_diff}">{formatar_moeda_br(abs(diff))}</div>
            </div>""", unsafe_allow_html=True)

        st.write("")

        # 2. Gráficos
        g1, g2 = st.columns(2)
        with g1:
            st.subheader("Evolução Pagamentos")
            if not df_p.empty:
                chart_p = alt.Chart(df_p).mark_bar(color='#10b981', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_p']['data'], axis=alt.Axis(format='%d/%m', title='Data')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_p']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_p, use_container_width=True)

        with g2:
            st.subheader("Previsão de Saídas")
            if not data['apagar'].empty:
                chart_a = alt.Chart(data['apagar']).mark_bar(color='#f59e0b', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_a']['data'], axis=alt.Axis(format='%d/%m', title='Vencimento')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_a']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_a, use_container_width=True)

    # --- ÁREA EXCLUSIVA: PDF E WHATSAPP ---
    if not mode_apresentacao:
        st.divider()
        st.subheader("📤 Exportação e Envio")

        tab_pdf, tab_wpp = st.tabs(["📄 Relatório PDF Completo", "📱 Mensagem Executiva"])

        with tab_pdf:
            st.write("Relatório oficial com capa, KPIs e detalhamento completo de todas as contas.")

            # Geração de PDF automática na memória (sem botão intermediário)
            try:
                logo_temp_path = None
                if uploaded_logo:
                    with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                        tmp.write(uploaded_logo.getvalue())
                        logo_temp_path = tmp.name

                pdf = PDFProfissional(logo_temp_path, f"Periodo: {data['periodo_txt']}", "Relatorio de Contas Pagas e A Pagar")
                pdf.add_page()

                # KPIs
                pdf.kpi_card(f"TOTAL PAGO ({data['dates']['p_str']})", formatar_moeda_br(total_pago), 10, 50)
                pdf.kpi_card(f"A PAGAR ({data['dates']['a_str']})", formatar_moeda_br(total_apagar), 75, 50)
                pdf.kpi_card("VARIACAO DE FLUXO", formatar_moeda_br(abs(diff)), 140, 50)
                pdf.ln(45)

                # Tabela 1: Contas Pagas
                pdf.chapter_title("Contas Pagas - Detalhamento")
                if not df_p.empty:
                    cols_p_pdf = [data['cols_p']['data'], data['cols_p']['desc']]
                    has_cat_p = data['cols_p']['cat'] in df_p.columns
                    if has_cat_p: cols_p_pdf.append(data['cols_p']['cat'])

                    full_p = df_p.sort_values(by=data['cols_p']['data']).copy()

                    # Prepara DF para tabela PDF
                    pdf_df_p = pd.DataFrame()
                    pdf_df_p['Data'] = full_p[data['cols_p']['data']].dt.strftime('%d/%m')
                    pdf_df_p['Fornecedor'] = full_p[data['cols_p']['desc']]
                    if has_cat_p: pdf_df_p['Categoria'] = full_p[data['cols_p']['cat']]
                    pdf_df_p['Valor'] = full_p['valor_final'].apply(formatar_moeda_br)

                    pdf.create_table(pdf_df_p, include_cat=has_cat_p)
                else:
                    pdf.set_font("Arial", "", 10)
                    pdf.cell(0, 10, "Nenhum pagamento registrado no periodo.", 0, 1)
                pdf.ln(10)

                # Tabela 2: Contas a Pagar
                pdf.chapter_title("Contas a Pagar - Previsao")
                if not data['apagar'].empty:
                    cols_a_pdf = [data['cols_a']['data'], data['cols_a']['desc']]
                    has_cat_a = data['cols_a']['cat'] in data['apagar'].columns
                    if has_cat_a: cols_a_pdf.append(data['cols_a']['cat'])

                    full_a = data['apagar'].sort_values(by=data['cols_a']['data']).copy()

                    pdf_df_a = pd.DataFrame()
                    pdf_df_a['Data'] = full_a[data['cols_a']['data']].dt.strftime('%d/%m')
                    pdf_df_a['Fornecedor'] = full_a[data['cols_a']['desc']]
                    if has_cat_a: pdf_df_a['Categoria'] = full_a[data['cols_a']['cat']]
                    pdf_df_a['Valor'] = full_a['valor_final'].apply(formatar_moeda_br)

                    pdf.create_table(pdf_df_a, include_cat=has_cat_a)
                else:
                    pdf.set_font("Arial", "", 10)
                    pdf.cell(0, 10, "Nenhuma conta a vencer no periodo.", 0, 1)

                pdf_bytes = pdf.output(dest='S').encode('latin-1')

                # Botão de Download Direto
                st.download_button(
                    label="⬇️ Baixar Relatório PDF",
                    data=pdf_bytes,
                    file_name="Relatorio_Financeiro_Completo.pdf",
                    mime='application/pdf'
                )

                if logo_temp_path: os.remove(logo_temp_path)

            except Exception as e:
                st.warning(f"Aguardando processamento ou erro na geração do PDF: {e}")

        with tab_wpp:
            # Mensagem Executiva e Profissional
            maior_forn_val = df_p.nlargest(1, 'valor_final')
            if not maior_forn_val.empty:
                nome_maior = maior_forn_val.iloc[0][data['cols_p']['desc']]
                val_maior = formatar_moeda_br(maior_forn_val.iloc[0]['valor_final'])
                txt_maior = f"• Maior despesa: {nome_maior} ({val_maior})"
            else:
                txt_maior = ""

            status_fluxo = "🔻 Redução" if diff < 0 else "🔺 Aumento"

            msg = f"""*RESUMO FINANCEIRO SEMANAL* 💼
_Controle de Contas Pagas e A Pagar_

🗓️ *Período Geral:* {data['periodo_txt']}

✅ *REALIZADO ({data['dates']['p_str']})*
• Total Pago: {formatar_moeda_br(total_pago)}
{txt_maior}

📅 *PREVISÃO ({data['dates']['a_str']})*
• Total a Vencer: {formatar_moeda_br(total_apagar)}
• Quantidade: {len(data['apagar'])} boletos

📉 *STATUS DO FLUXO*
• Variação: {status_fluxo} de {formatar_moeda_br(abs(diff))} em relação à semana anterior."""

            st.markdown("##### Copie a mensagem abaixo:")
            st.code(msg, language="markdown")

else:
    st.info("👋 Para começar, faça o upload dos arquivos 'Contas Pagas' e 'A Pagar' na barra lateral.")