# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiAwg4PtamB0Gn75gJJieE2QGC7QEhs5
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime, timedelta

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(
    page_title="Gerador de Relatório Financeiro",
    page_icon="📊",
    layout="wide"
)

# --- ESTILOS CSS (Visual Premium) ---
st.markdown("""
    <style>
    /* Estilo do Cartão de Relatório */
    .report-container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 15px;
        border: 1px solid #e0e0e0;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        margin-bottom: 20px;
    }
    .report-title {
        font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
        color: #1f2937;
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 5px;
        border-bottom: 2px solid #3b82f6;
        padding-bottom: 10px;
    }
    .report-subtitle {
        color: #6b7280;
        font-size: 14px;
        margin-bottom: 20px;
    }
    /* Métricas */
    div[data-testid="stMetric"] {
        background-color: #f9fafb;
        border: 1px solid #e5e7eb;
        border-radius: 8px;
        padding: 10px;
        text-align: center;
    }
    div[data-testid="stMetricLabel"] {
        font-size: 14px;
        font-weight: bold;
        color: #555;
    }
    </style>
    """, unsafe_allow_html=True)

# --- FUNÇÕES AUXILIARES ---
def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith('.xlsx') or uploaded_file.name.endswith('.xls'):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except Exception as e:
        st.error(f"Erro ao ler arquivo: {e}")
        return None

def limpar_valor_moeda(valor):
    """Retorna sempre o valor absoluto (positivo) para gráficos e somas"""
    val_float = 0.0
    if isinstance(valor, (int, float)):
        val_float = float(valor)
    elif isinstance(valor, str):
        # Remove caracteres de moeda e converte
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: val_float = float(limpo)
        except: val_float = 0.0

    return abs(val_float) # Força positivo com abs()

def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def selecionar_coluna(df, label, key_suffix, keywords):
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break
    return st.selectbox(f"Coluna de **{label}**:", cols, index=default_idx, key=f"sel_{key_suffix}")

# --- GRÁFICOS MELHORADOS ---
def criar_grafico_barras(df, x_col, y_col, cor, titulo):
    # Base do gráfico
    base = alt.Chart(df, title=titulo).encode(
        x=alt.X(x_col, axis=alt.Axis(format='%d/%m', title=None, labelAngle=0)),
        y=alt.Y(y_col, axis=alt.Axis(title=None, grid=False, labels=False)), # Remove eixo Y para limpar
        tooltip=[alt.Tooltip(x_col, format='%d/%m'), alt.Tooltip(y_col, format=',.2f')]
    )

    # As Barras
    barras = base.mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3, size=25).encode(
        color=alt.value(cor)
    )

    # Os Rótulos (Texto em cima da barra)
    textos = base.mark_text(dy=-10, color='black', size=11).encode(
        text=alt.Text(y_col, format=',.0f') # Formata sem decimais para economizar espaço
    )

    return (barras + textos).properties(height=220)

def criar_grafico_ranking(df, cat_col, val_col, titulo, cor):
    # Agrupa e pega top 5
    top_df = df.groupby(cat_col)[val_col].sum().reset_index().nlargest(5, val_col)

    base = alt.Chart(top_df, title=titulo).encode(
        x=alt.X(val_col, axis=alt.Axis(labels=False, title=None, grid=False)),
        y=alt.Y(cat_col, sort='-x', title=None, axis=alt.Axis(labelLimit=150)),
        tooltip=[cat_col, alt.Tooltip(val_col, format=',.2f')]
    )

    barras = base.mark_bar(cornerRadiusTopRight=3, cornerRadiusBottomRight=3).encode(
        color=alt.value(cor)
    )

    textos = base.mark_text(align='left', dx=5, color='black').encode(
        text=alt.Text(val_col, format=',.0f')
    )

    return (barras + textos).properties(height=250)

# --- INTERFACE PRINCIPAL ---

# BARRA LATERAL (CONFIGURAÇÕES)
with st.sidebar:
    st.header("⚙️ Configurações")
    data_ref = st.date_input("Data de Referência", datetime.now())

    # Datas
    inicio_semana_atual = data_ref - timedelta(days=data_ref.weekday())
    fim_semana_atual = inicio_semana_atual + timedelta(days=6)
    inicio_semana_passada = inicio_semana_atual - timedelta(days=7)
    fim_semana_passada = inicio_semana_atual - timedelta(days=1)

    str_passada = f"{inicio_semana_passada.strftime('%d/%m')} a {fim_semana_passada.strftime('%d/%m')}"
    str_atual = f"{inicio_semana_atual.strftime('%d/%m')} a {fim_semana_atual.strftime('%d/%m')}"

    st.markdown("---")
    st.markdown("### 📂 Upload de Arquivos")
    arquivo_pagas = st.file_uploader("1. Contas PAGAS (Semana Passada)", type=['csv', 'xlsx'])
    arquivo_apagar = st.file_uploader("2. Contas A PAGAR (Esta Semana)", type=['csv', 'xlsx'])

# VARIÁVEIS GLOBAIS
total_pago = 0.0
total_a_pagar = 0.0
df_pagas_final = pd.DataFrame()
df_apagar_final = pd.DataFrame()

# --- PROCESSAMENTO ---
if arquivo_pagas and arquivo_apagar:

    # Processamento silencioso
    with st.sidebar.expander("🔧 Ajuste de Colunas", expanded=False):
        st.markdown("**Contas Pagas**")
        df_pagas = carregar_dados(arquivo_pagas)
        if df_pagas is not None:
            col_data_p = selecionar_coluna(df_pagas, "Data Pagamento", "pagas_data", ['pagamento', 'baixa', 'data'])
            col_val_p = selecionar_coluna(df_pagas, "Valor", "pagas_valor", ['valor pago', 'valor', 'total'])
            col_desc_p = selecionar_coluna(df_pagas, "Fornecedor/Desc", "pagas_desc", ['fornecedor', 'descrição', 'nome'])

            df_pagas[col_data_p] = pd.to_datetime(df_pagas[col_data_p], dayfirst=True, errors='coerce')
            df_pagas['valor_tratado'] = df_pagas[col_val_p].apply(limpar_valor_moeda)
            mask_p = (df_pagas[col_data_p].dt.date >= inicio_semana_passada) & (df_pagas[col_data_p].dt.date <= fim_semana_passada)
            df_pagas_final = df_pagas[mask_p].copy()
            total_pago = df_pagas_final['valor_tratado'].sum()

        st.markdown("---")
        st.markdown("**Contas A Pagar**")
        df_apagar = carregar_dados(arquivo_apagar)
        if df_apagar is not None:
            col_data_a = selecionar_coluna(df_apagar, "Data Vencimento", "apagar_data", ['vencimento', 'data'])
            col_val_a = selecionar_coluna(df_apagar, "Valor", "apagar_valor", ['valor líquido', 'valor', 'aberto'])
            col_desc_a = selecionar_coluna(df_apagar, "Fornecedor/Desc", "apagar_desc", ['fornecedor', 'descrição', 'nome'])

            df_apagar[col_data_a] = pd.to_datetime(df_apagar[col_data_a], dayfirst=True, errors='coerce')
            df_apagar['valor_tratado'] = df_apagar[col_val_a].apply(limpar_valor_moeda)
            mask_a = (df_apagar[col_data_a].dt.date >= inicio_semana_atual) & (df_apagar[col_data_a].dt.date <= fim_semana_atual)
            df_apagar_final = df_apagar[mask_a].copy()
            total_a_pagar = df_apagar_final['valor_tratado'].sum()

    # --- ÁREA VISUAL (RELATÓRIO PARA PRINT) ---
    with st.container():
        st.markdown('<div class="report-container">', unsafe_allow_html=True)

        # Cabeçalho
        st.markdown('<div class="report-title">📑 Resumo Semanal de Pagamentos</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="report-subtitle">Análise de Saídas: {str_passada} vs {str_atual}</div>', unsafe_allow_html=True)

        # Métricas (KPIs)
        col_kpi1, col_kpi2, col_kpi3 = st.columns(3)
        col_kpi1.metric("PAGO (Semana Passada)", formatar_moeda_br(total_pago), delta="Realizado")
        col_kpi2.metric("A PAGAR (Esta Semana)", formatar_moeda_br(total_a_pagar), delta="Previsão", delta_color="inverse")

        # Lógica do KPI de Comparação (Mais clara agora)
        diff = total_a_pagar - total_pago
        if diff > 0:
            msg_diff = "🔺 Aumentará pagamentos"
            color_diff = "inverse" # Vermelho (alerta)
        elif diff < 0:
            msg_diff = "🔻 Reduzirá pagamentos"
            color_diff = "normal" # Verde (economia)
        else:
            msg_diff = "Estável"
            color_diff = "off"

        col_kpi3.metric("Comparativo de Saídas", formatar_moeda_br(abs(diff)), delta=msg_diff, delta_color=color_diff)

        st.markdown("---")

        # Gráficos Linha 1: Evolução Diária
        c_g1, c_g2 = st.columns(2)
        with c_g1:
            if not df_pagas_final.empty:
                chart_data_p = df_pagas_final.groupby(col_data_p)['valor_tratado'].sum().reset_index()
                st.altair_chart(criar_grafico_barras(chart_data_p, col_data_p, 'valor_tratado', '#10b981', "Evolução Pagamentos (Dia a Dia)"), use_container_width=True)
            else:
                st.info("Sem pagamentos no período.")

        with c_g2:
            if not df_apagar_final.empty:
                chart_data_a = df_apagar_final.groupby(col_data_a)['valor_tratado'].sum().reset_index()
                st.altair_chart(criar_grafico_barras(chart_data_a, col_data_a, 'valor_tratado', '#f59e0b', "Previsão de Saída (Por Vencimento)"), use_container_width=True)
            else:
                st.info("Sem contas a vencer.")

        # Gráfico Linha 2: Top Fornecedores
        st.markdown("#### 🏆 Top 5 Maiores Fornecedores (Pagos)")
        if not df_pagas_final.empty:
            st.altair_chart(criar_grafico_ranking(df_pagas_final, col_desc_p, 'valor_tratado', '', '#3b82f6'), use_container_width=True)
        else:
            st.caption("Sem dados.")

        st.markdown('</div>', unsafe_allow_html=True)

    # --- TEXTO WHATSAPP ---
    st.markdown("### 📲 Texto para WhatsApp")

    top_3 = df_pagas_final.nlargest(3, 'valor_tratado')
    lista_pagas = ""
    for _, row in top_3.iterrows():
        lista_pagas += f"▫️ {row[col_desc_p]}: {formatar_moeda_br(row['valor_tratado'])}\n"
    if lista_pagas == "": lista_pagas = "▫️ Sem destaques.\n"

    mensagem = f"""Bom dia! ☀️
*Resumo de Contas Pagas e Previsão*

✅ *REALIZADO ({str_passada})*
Total Pago: *{formatar_moeda_br(total_pago)}*

Principais saídas:
{lista_pagas}

📅 *PREVISÃO ({str_atual})*
Total a Vencer: *{formatar_moeda_br(total_a_pagar)}*
Qtd. boletos: {len(df_apagar_final)}

Qualquer dúvida, estou à disposição!"""

    st.text_area("Copiar mensagem:", value=mensagem, height=350)

else:
    st.info("👋 Faça o upload dos arquivos 'Contas Pagas' e 'Contas a Pagar' na barra lateral para gerar o relatório.")