# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HW9be_YqaA5DVy1cVkGIaOLHjPVcQ5No
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime
import tempfile
import os
from fpdf import FPDF

# --- CONFIGURAÇÃO INICIAL ---
st.set_page_config(
    page_title="Dashboard Financeiro Executivo",
    page_icon="💎",
    layout="wide"
)

# --- ESTILOS CSS ---
st.markdown("""
    <style>
    .report-container {
        background-color: white;
        padding: 2rem;
        border-radius: 12px;
        box-shadow: 0 4px 20px rgba(0,0,0,0.08);
        border: 1px solid #f0f0f0;
    }
    .kpi-card {
        background-color: #f8f9fa;
        border-radius: 10px;
        padding: 20px;
        border-left: 6px solid #3b82f6;
        box-shadow: 0 2px 5px rgba(0,0,0,0.05);
        transition: transform 0.2s;
    }
    .kpi-card:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
    }
    .big-number { font-size: 26px; font-weight: 800; color: #1f2937; margin-top: 8px; font-family: 'Helvetica Neue', sans-serif; }
    .small-label { font-size: 13px; color: #64748b; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; }
    h4 { color: #334155; font-weight: 600; }
    </style>
""", unsafe_allow_html=True)

# --- FUNÇÕES DE UTILIDADE ---
def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def limpar_valor_moeda(valor):
    if isinstance(valor, (int, float)): return abs(float(valor))
    if isinstance(valor, str):
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: return abs(float(limpo))
        except: return 0.0
    return 0.0

def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith(('.xlsx', '.xls')):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except: return None

def selecionar_coluna(df, label, key_suffix, keywords):
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break

    key = f"sel_{key_suffix}"
    if key not in st.session_state:
        st.session_state[key] = cols[default_idx] if cols else None

    selected = st.selectbox(f"{label}", cols, index=default_idx, key=key)
    return selected

# --- CLASSE PDF PROFISSIONAL (PREMIUM) ---
class PDFPremium(FPDF):
    def __init__(self, logo_path=None, periodo="", titulo="Relatório Executivo"):
        super().__init__()
        self.logo_path = logo_path
        self.periodo = periodo
        self.titulo_relatorio = titulo

    def header(self):
        # Apenas desenha a barra azul em todas as páginas
        self.set_fill_color(30, 64, 175) # Azul Profundo
        self.rect(0, 0, 210, 5, 'F')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Página {self.page_no()}', 0, 0, 'C')

    def cover_page(self, kpis):
        """Gera uma capa elegante"""
        self.add_page()

        # Logo na Capa (Grande)
        if self.logo_path:
            try:
                # Centralizado
                x_logo = (210 - 50) / 2
                self.image(self.logo_path, x_logo, 30, 50)
            except: pass

        self.ln(80 if self.logo_path else 40)

        # Título Grande
        self.set_font('Arial', 'B', 24)
        self.set_text_color(33, 33, 33)
        self.cell(0, 10, self.titulo_relatorio.upper(), 0, 1, 'C')

        self.ln(5)
        self.set_font('Arial', '', 12)
        self.set_text_color(100)
        self.cell(0, 10, f"Período de Análise: {self.periodo}", 0, 1, 'C')

        self.ln(20)

        # Caixa de Resumo Executivo (KPIs)
        self.set_fill_color(248, 250, 252)
        self.set_draw_color(226, 232, 240)
        # x, y, w, h
        x_start = 35
        y_start = self.get_y()
        self.rect(x_start, y_start, 140, 80, 'FD')

        self.set_xy(x_start, y_start + 10)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(30, 64, 175)
        self.cell(140, 10, "Destaques da Semana", 0, 1, 'C')

        self.ln(5)

        # KPI 1
        self.set_x(x_start)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100)
        self.cell(140, 6, "TOTAL PAGO", 0, 1, 'C')
        self.set_x(x_start)
        self.set_font('Arial', 'B', 16)
        self.set_text_color(33)
        self.cell(140, 8, kpis['pago'], 0, 1, 'C')

        self.ln(5)

        # KPI 2
        self.set_x(x_start)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100)
        self.cell(140, 6, "A PAGAR (PREVISÃO)", 0, 1, 'C')
        self.set_x(x_start)
        self.set_font('Arial', 'B', 16)
        self.set_text_color(33)
        self.cell(140, 8, kpis['apagar'], 0, 1, 'C')

        self.ln(5)

        # KPI 3
        self.set_x(x_start)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100)
        self.cell(140, 6, "VARIAÇÃO DE FLUXO", 0, 1, 'C')
        self.set_x(x_start)
        self.set_font('Arial', 'B', 16)
        self.cell(140, 8, kpis['diff'], 0, 1, 'C')

    def section_title(self, title):
        self.ln(10)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(30, 64, 175)
        self.cell(0, 10, title.upper(), 0, 1, 'L')
        self.set_draw_color(30, 64, 175)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def create_table(self, df, include_cat=False):
        # Configuração das Colunas
        if include_cat:
            headers = ["Data", "Fornecedor", "Categoria", "Valor"]
            widths = [25, 85, 45, 35]
        else:
            headers = ["Data", "Fornecedor", "Valor"]
            widths = [30, 115, 45]

        # Header Tabela
        self.set_font('Arial', 'B', 9)
        self.set_fill_color(241, 245, 249)
        self.set_text_color(33)
        self.set_draw_color(200)

        for i, h in enumerate(headers):
            self.cell(widths[i], 8, str(h), 1, 0, 'C', 1)
        self.ln()

        # Linhas
        self.set_font('Arial', '', 9)
        fill = False

        for _, row in df.iterrows():
            # Extração de dados segura
            dt = str(row[0])
            forn = str(row[1])[:50]
            try: forn = forn.encode('latin-1', 'replace').decode('latin-1')
            except: pass

            if include_cat:
                cat = str(row[2])[:25]
                try: cat = cat.encode('latin-1', 'replace').decode('latin-1')
                except: pass
                val = str(row[3])

                self.cell(widths[0], 7, dt, 1, 0, 'C', fill)
                self.cell(widths[1], 7, forn, 1, 0, 'L', fill)
                self.cell(widths[2], 7, cat, 1, 0, 'L', fill)
                self.cell(widths[3], 7, val, 1, 1, 'R', fill)
            else:
                val = str(row[2])
                self.cell(widths[0], 7, dt, 1, 0, 'C', fill)
                self.cell(widths[1], 7, forn, 1, 0, 'L', fill)
                self.cell(widths[2], 7, val, 1, 1, 'R', fill)

            self.ln()
            self.set_draw_color(230)
            self.line(10, self.get_y(), 200, self.get_y())

# --- FUNÇÃO ISOLADA DE GERAÇÃO DE PDF ---
def gerar_pdf_bytes(data, uploaded_logo, total_pago, total_apagar, diff):
    try:
        logo_temp_path = None
        if uploaded_logo:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                tmp.write(uploaded_logo.getvalue())
                logo_temp_path = tmp.name

        pdf = PDFPremium(logo_temp_path, data['periodo_txt'], "Relatório Financeiro Semanal")

        # CAPA
        kpis = {
            'pago': formatar_moeda_br(total_pago),
            'apagar': formatar_moeda_br(total_apagar),
            'diff': formatar_moeda_br(abs(diff)) + (" (Aumento)" if diff > 0 else " (Redução)")
        }
        pdf.cover_page(kpis)

        pdf.add_page() # Página de dados

        # TABELA 1: PAGOS
        pdf.section_title("Detalhamento: Contas Pagas")
        df_p = data['pagas']
        if not df_p.empty:
            cols_p_pdf = [data['cols_p']['data'], data['cols_p']['desc']]
            has_cat_p = data['cols_p']['cat'] in df_p.columns
            if has_cat_p: cols_p_pdf.append(data['cols_p']['cat'])

            full_p = df_p.sort_values(by=data['cols_p']['data']).copy()

            pdf_df_p = pd.DataFrame()
            pdf_df_p['Data'] = full_p[data['cols_p']['data']].dt.strftime('%d/%m')
            pdf_df_p['Fornecedor'] = full_p[data['cols_p']['desc']]
            if has_cat_p: pdf_df_p['Categoria'] = full_p[data['cols_p']['cat']]
            pdf_df_p['Valor'] = full_p['valor_final'].apply(formatar_moeda_br)

            pdf.create_table(pdf_df_p, include_cat=has_cat_p)

            # Resumo por Categoria (Se houver)
            if has_cat_p:
                pdf.ln(10)
                pdf.set_font('Arial', 'B', 11)
                pdf.cell(0, 10, "Resumo por Categoria:", 0, 1)
                resumo_cat = full_p.groupby(data['cols_p']['cat'])['valor_final'].sum().sort_values(ascending=False).reset_index()
                resumo_cat['valor_final'] = resumo_cat['valor_final'].apply(formatar_moeda_br)
                pdf.set_font('Arial', 'B', 9)
                pdf.cell(100, 7, "Categoria", 1)
                pdf.cell(40, 7, "Total", 1, 1)
                pdf.set_font('Arial', '', 9)
                for _, row in resumo_cat.iterrows():
                    cat_txt = str(row[0])[:50].encode('latin-1', 'replace').decode('latin-1')
                    pdf.cell(100, 7, cat_txt, 1)
                    pdf.cell(40, 7, str(row[1]), 1, 1)

        else:
            pdf.set_font("Arial", "", 10)
            pdf.cell(0, 10, "Sem registros.", 0, 1)

        pdf.ln(10)

        # TABELA 2: A PAGAR
        pdf.section_title("Previsão: Contas a Pagar")
        df_a = data['apagar']
        if not df_a.empty:
            cols_a_pdf = [data['cols_a']['data'], data['cols_a']['desc']]
            has_cat_a = data['cols_a']['cat'] in df_a.columns
            if has_cat_a: cols_a_pdf.append(data['cols_a']['cat'])

            full_a = df_a.sort_values(by=data['cols_a']['data']).copy()

            pdf_df_a = pd.DataFrame()
            pdf_df_a['Data'] = full_a[data['cols_a']['data']].dt.strftime('%d/%m')
            pdf_df_a['Fornecedor'] = full_a[data['cols_a']['desc']]
            if has_cat_a: pdf_df_a['Categoria'] = full_a[data['cols_a']['cat']]
            pdf_df_a['Valor'] = full_a['valor_final'].apply(formatar_moeda_br)

            pdf.create_table(pdf_df_a, include_cat=has_cat_a)
        else:
            pdf.set_font("Arial", "", 10)
            pdf.cell(0, 10, "Sem registros.", 0, 1)

        pdf_bytes = pdf.output(dest='S').encode('latin-1')
        if logo_temp_path: os.remove(logo_temp_path)
        return pdf_bytes

    except Exception as e:
        return None


# --- INTERFACE E LÓGICA ---

# Sidebar
with st.sidebar:
    st.header("1. Arquivos")
    uploaded_logo = st.file_uploader("Logo da Empresa (Opcional)", type=['png', 'jpg'])
    uploaded_pagas = st.file_uploader("Relatório: PAGAS", type=['csv', 'xlsx'])
    uploaded_apagar = st.file_uploader("Relatório: A PAGAR", type=['csv', 'xlsx'])
    st.divider()
    mode_apresentacao = st.toggle("📺 Modo Apresentação", value=False)

# Estado
if 'processed_data' not in st.session_state:
    st.session_state.processed_data = None

# Processamento
if not mode_apresentacao and uploaded_pagas and uploaded_apagar:

    with st.sidebar.expander("⚙️ Configurar Colunas", expanded=False):
        st.markdown("**1. Contas Pagas**")
        df_pagas = carregar_dados(uploaded_pagas)
        if df_pagas is not None:
            col_p_data = selecionar_coluna(df_pagas, "Data Pagamento", "p_data", ['data', 'pagamento'])
            col_p_val = selecionar_coluna(df_pagas, "Valor", "p_val", ['valor', 'pago', 'total'])
            col_p_desc = selecionar_coluna(df_pagas, "Fornecedor", "p_desc", ['fornecedor', 'nome', 'descrição'])
            col_p_cat = selecionar_coluna(df_pagas, "Categoria (Opcional)", "p_cat", ['categoria', 'classificação'])

        st.divider()
        st.markdown("**2. Contas a Pagar**")
        df_apagar = carregar_dados(uploaded_apagar)
        if df_apagar is not None:
            col_a_data = selecionar_coluna(df_apagar, "Data Vencimento", "a_data", ['vencimento', 'data'])
            col_a_val = selecionar_coluna(df_apagar, "Valor", "a_val", ['valor', 'líquido', 'aberto'])
            col_a_desc = selecionar_coluna(df_apagar, "Fornecedor", "a_desc", ['fornecedor', 'nome', 'descrição'])
            col_a_cat = selecionar_coluna(df_apagar, "Categoria (Opcional)", "a_cat", ['categoria', 'classificação'])

    if df_pagas is not None and df_apagar is not None:
        try:
            # Tratamento
            df_pagas[col_p_data] = pd.to_datetime(df_pagas[col_p_data], dayfirst=True, errors='coerce')
            df_pagas['valor_final'] = df_pagas[col_p_val].apply(limpar_valor_moeda)
            df_pagas = df_pagas.dropna(subset=[col_p_data])

            str_periodo_pagas = "N/A"
            if not df_pagas.empty:
                str_periodo_pagas = f"{df_pagas[col_p_data].min().strftime('%d/%m')} a {df_pagas[col_p_data].max().strftime('%d/%m')}"

            df_apagar[col_a_data] = pd.to_datetime(df_apagar[col_a_data], dayfirst=True, errors='coerce')
            df_apagar['valor_final'] = df_apagar[col_a_val].apply(limpar_valor_moeda)
            df_apagar = df_apagar.dropna(subset=[col_a_data])

            str_periodo_apagar = "N/A"
            if not df_apagar.empty:
                str_periodo_apagar = f"{df_apagar[col_a_data].min().strftime('%d/%m')} a {df_apagar[col_a_data].max().strftime('%d/%m')}"

            st.session_state.processed_data = {
                'pagas': df_pagas,
                'apagar': df_apagar,
                'cols_p': {'data': col_p_data, 'val': 'valor_final', 'desc': col_p_desc, 'cat': col_p_cat},
                'cols_a': {'data': col_a_data, 'val': 'valor_final', 'desc': col_a_desc, 'cat': col_a_cat},
                'periodo_txt': f"{str_periodo_pagas} e {str_periodo_apagar}",
                'dates': {'p_str': str_periodo_pagas, 'a_str': str_periodo_apagar},
                'totals': {
                    'pago': df_pagas['valor_final'].sum(),
                    'apagar': df_apagar['valor_final'].sum()
                }
            }
        except Exception as e:
            st.error(f"Erro ao processar dados: {e}")

# --- RENDERIZAÇÃO ---
data = st.session_state.processed_data

if data:
    df_p = data['pagas'].copy()
    if not mode_apresentacao and data['cols_p']['cat'] in df_p.columns:
        st.sidebar.divider()
        st.sidebar.markdown("🔎 **Filtros**")
        cats = sorted(list(df_p[data['cols_p']['cat']].astype(str).unique()))
        sel_cat = st.sidebar.multiselect("Filtrar Categoria", cats)
        if sel_cat:
            df_p = df_p[df_p[data['cols_p']['cat']].astype(str).isin(sel_cat)]

    total_pago = df_p['valor_final'].sum()
    total_apagar = data['totals']['apagar']

    with st.container():
        if mode_apresentacao:
            st.markdown("### 📺 Modo Apresentação")
            st.markdown(f"# Resultados Financeiros")
            st.markdown(f"*{data['periodo_txt']}*")
        else:
            st.markdown(f"## 📑 Dashboard Financeiro Executivo")
            st.markdown(f"**Período:** {data['periodo_txt']}")
        st.markdown("---")

        # KPIs
        k1, k2, k3 = st.columns(3)
        diff = total_apagar - total_pago

        with k1:
            st.markdown(f"""
            <div class="kpi-card">
                <div class="small-label">TOTAL PAGO ({data['dates']['p_str']})</div>
                <div class="big-number" style="color:#10b981">{formatar_moeda_br(total_pago)}</div>
            </div>""", unsafe_allow_html=True)

        with k2:
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: #f59e0b;">
                <div class="small-label">A PAGAR ({data['dates']['a_str']})</div>
                <div class="big-number" style="color:#d97706">{formatar_moeda_br(total_apagar)}</div>
            </div>""", unsafe_allow_html=True)

        with k3:
            lbl_diff = "AUMENTO DE FLUXO" if diff > 0 else "REDUÇÃO DE FLUXO"
            cor_diff = "#ef4444" if diff > 0 else "#10b981"
            st.markdown(f"""
            <div class="kpi-card" style="border-left-color: {cor_diff};">
                <div class="small-label">{lbl_diff}</div>
                <div class="big-number" style="color:{cor_diff}">{formatar_moeda_br(abs(diff))}</div>
            </div>""", unsafe_allow_html=True)

        st.write("")

        # Gráficos de Evolução
        g1, g2 = st.columns(2)
        with g1:
            st.subheader("📈 Evolução dos Pagamentos")
            if not df_p.empty:
                chart_p = alt.Chart(df_p).mark_bar(color='#10b981', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_p']['data'], axis=alt.Axis(format='%d/%m', title='Data')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_p']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_p, use_container_width=True)

        with g2:
            st.subheader("📊 Previsão Diária")
            if not data['apagar'].empty:
                chart_a = alt.Chart(data['apagar']).mark_bar(color='#f59e0b', cornerRadiusTopLeft=5, cornerRadiusTopRight=5).encode(
                    x=alt.X(data['cols_a']['data'], axis=alt.Axis(format='%d/%m', title='Vencimento')),
                    y=alt.Y('valor_final', axis=alt.Axis(labels=False, title=None, grid=False)),
                    tooltip=[data['cols_a']['desc'], alt.Tooltip('valor_final', format=',.2f')]
                ).properties(height=250)
                st.altair_chart(chart_a, use_container_width=True)

        st.divider()

        # ÁREA DE DESTAQUES E RANKINGS (RESTAURADA E MELHORADA)
        st.subheader("🏆 Destaques e Rankings")
        r1, r2 = st.columns(2)

        with r1:
            st.markdown("##### 📉 Maiores Saídas (Realizado)")
            if not df_p.empty:
                # Agrupa por fornecedor para somar pagamentos múltiplos
                top_p = df_p.groupby(data['cols_p']['desc'])['valor_final'].sum().nlargest(5).reset_index()
                top_p.columns = ['Fornecedor', 'Valor']
                st.dataframe(
                    top_p,
                    column_config={
                        "Valor": st.column_config.ProgressColumn(
                            "Total Pago",
                            format="R$ %.2f",
                            min_value=0,
                            max_value=top_p['Valor'].max(),
                        ),
                    },
                    hide_index=True,
                    use_container_width=True
                )
            else:
                st.info("Sem dados.")

        with r2:
            st.markdown("##### ⚠️ Próximos Vencimentos (Top 5)")
            if not data['apagar'].empty:
                top_a = data['apagar'].nlargest(5, 'valor_final')[[data['cols_a']['data'], data['cols_a']['desc'], 'valor_final']]
                top_a.columns = ['Vencimento', 'Fornecedor', 'Valor']
                st.dataframe(
                    top_a,
                    column_config={
                        "Vencimento": st.column_config.DateColumn(format="DD/MM/YYYY"),
                        "Valor": st.column_config.ProgressColumn(
                            "Valor do Boleto",
                            format="R$ %.2f",
                            min_value=0,
                            max_value=top_a['Valor'].max(),
                            help="Barra visual proporcional ao valor"
                        ),
                    },
                    hide_index=True,
                    use_container_width=True
                )
            else:
                st.info("Sem dados.")

        # BÔNUS: GRÁFICO DE CATEGORIA
        if data['cols_p']['cat'] in df_p.columns:
            st.divider()
            st.subheader("🧩 Distribuição por Categoria")
            c_cat1, c_cat2 = st.columns([2, 1])
            with c_cat1:
                cat_chart_data = df_p.groupby(data['cols_p']['cat'])['valor_final'].sum().reset_index()
                cat_chart_data.columns = ['Categoria', 'Valor']

                base = alt.Chart(cat_chart_data).encode(
                    theta=alt.Theta("Valor", stack=True)
                )
                pie = base.mark_arc(outerRadius=120).encode(
                    color=alt.Color("Categoria"),
                    order=alt.Order("Valor", sort="descending"),
                    tooltip=["Categoria", alt.Tooltip("Valor", format=",.2f")]
                )
                text = base.mark_text(radius=140).encode(
                    text=alt.Text("Valor", format=",.2f"),
                    order=alt.Order("Valor", sort="descending"),
                    color=alt.value("black")
                )
                st.altair_chart(pie + text, use_container_width=True)
            with c_cat2:
                st.info("💡 Este gráfico ajuda a entender onde o dinheiro está sendo alocado (ex: Pessoal, Impostos, Fornecedores).")

    # EXPORTAÇÃO E MENSAGEM
    if not mode_apresentacao:
        st.divider()
        st.subheader("📤 Exportação e Envio")

        tab_pdf, tab_wpp = st.tabs(["📄 Relatório PDF Premium", "📱 Mensagem WhatsApp"])

        with tab_pdf:
            st.write("Baixe o relatório completo com capa e detalhamento.")

            # GERA PDF
            pdf_bytes = gerar_pdf_bytes(data, uploaded_logo, total_pago, total_apagar, diff)

            if pdf_bytes:
                st.download_button(
                    label="⬇️ Baixar PDF Completo",
                    data=pdf_bytes,
                    file_name="Relatorio_Financeiro.pdf",
                    mime='application/pdf'
                )
            else:
                st.error("Erro ao gerar PDF. Verifique os dados.")

        with tab_wpp:
            # Mensagem Melhorada
            maior_forn_val = df_p.nlargest(1, 'valor_final')
            txt_maior = ""
            if not maior_forn_val.empty:
                nome = maior_forn_val.iloc[0][data['cols_p']['desc']]
                val = formatar_moeda_br(maior_forn_val.iloc[0]['valor_final'])
                txt_maior = f"🔝 *Maior Desembolso:* {nome} ({val})"

            # Ícones de status
            icon_diff = "🔴" if diff > 0 else "🟢"
            txt_diff = "Aumento de Despesas" if diff > 0 else "Redução de Despesas"

            msg = f"""*RELATÓRIO FINANCEIRO SEMANAL* 💼

📅 *Período:* {data['periodo_txt']}

━━━━━━━━━━━━━━━━━━━
✅ *CONTAS PAGAS*
💰 Total: {formatar_moeda_br(total_pago)}
{txt_maior}
━━━━━━━━━━━━━━━━━━━
⚠️ *A PAGAR (Previsão)*
💰 Total: {formatar_moeda_br(total_apagar)}
📄 Boletos: {len(data['apagar'])} un.
━━━━━━━━━━━━━━━━━━━
📊 *VARIAÇÃO DE FLUXO*
{icon_diff} {txt_diff}: {formatar_moeda_br(abs(diff))}
"""
            st.markdown("##### Copiar Mensagem:")
            st.code(msg, language="markdown")

else:
    st.info("👋 Para começar, faça o upload dos arquivos 'Contas Pagas' e 'A Pagar' na barra lateral.")