# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbnV4VPPFLkciMdghSz6_AkF8cQfOvAa
"""

import streamlit as st
import pandas as pd
from datetime import datetime, timedelta

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(
    page_title="Gerador de Relatório Financeiro",
    page_icon="💼",
    layout="wide"
)

# --- ESTILOS CSS ---
st.markdown("""
    <style>
    .stMetric { background-color: #f8f9fa; padding: 15px; border-radius: 10px; border: 1px solid #e0e0e0; }
    .css-1d391kg { padding-top: 1rem; }
    </style>
    """, unsafe_allow_html=True)

# --- FUNÇÕES AUXILIARES ---
def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith('.xlsx') or uploaded_file.name.endswith('.xls'):
            return pd.read_excel(uploaded_file)
        else:
            # Tenta ler CSV com diferentes separadores e encodings
            try:
                return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except:
                return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except Exception as e:
        st.error(f"Erro ao ler arquivo: {e}")
        return None

def limpar_valor_moeda(valor):
    """Converte strings tipo 'R$ 1.200,50' para float 1200.50"""
    if isinstance(valor, (int, float)):
        return valor
    if isinstance(valor, str):
        # Remove R$, espaços e pontos de milhar
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '')
        # Troca a vírgula decimal por ponto
        limpo = limpo.replace(',', '.')
        try:
            return float(limpo)
        except:
            return 0.0
    return 0.0

def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def selecionar_coluna(df, label, key_suffix, keywords):
    """Cria um dropdown inteligente que tenta adivinhar a coluna"""
    cols = list(df.columns)
    # Tenta encontrar uma coluna que contenha uma das palavras-chave
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break

    return st.selectbox(f"Selecione a coluna de **{label}**:", cols, index=default_idx, key=f"sel_{key_suffix}")

# --- INTERFACE PRINCIPAL ---
st.title("💼 Gerador de Briefing Financeiro")
st.markdown("---")

# BARRA LATERAL - Uploads e Datas
with st.sidebar:
    st.header("1. Configuração de Data")
    data_ref = st.date_input("Data de Referência (Hoje)", datetime.now())

    # Cálculo das semanas
    inicio_semana_atual = data_ref - timedelta(days=data_ref.weekday())
    fim_semana_atual = inicio_semana_atual + timedelta(days=6)
    inicio_semana_passada = inicio_semana_atual - timedelta(days=7)
    fim_semana_passada = inicio_semana_atual - timedelta(days=1)

    st.info(f"⏪ **Passado:** {inicio_semana_passada.strftime('%d/%m')} a {fim_semana_passada.strftime('%d/%m')}")
    st.info(f"⏩ **Futuro:** {inicio_semana_atual.strftime('%d/%m')} a {fim_semana_atual.strftime('%d/%m')}")

    st.markdown("---")
    st.header("2. Arquivos")
    arquivo_pagas = st.file_uploader("📂 Upload: Contas PAGAS (Semana Passada)", type=['csv', 'xlsx'])
    arquivo_apagar = st.file_uploader("📂 Upload: Contas A PAGAR (Esta Semana)", type=['csv', 'xlsx'])

# --- PROCESSAMENTO DOS DADOS ---

# Variáveis para armazenar resultados finais
texto_pagas = "Nenhum dado carregado."
texto_apagar = "Nenhum dado carregado."
total_pago = 0.0
total_a_pagar = 0.0
df_pagas_final = pd.DataFrame()
df_apagar_final = pd.DataFrame()

col1, col2 = st.columns(2)

# --- BLOCO 1: CONTAS PAGAS ---
with col1:
    st.subheader("✅ Realizado (Semana Passada)")
    if arquivo_pagas:
        df_pagas = carregar_dados(arquivo_pagas)
        if df_pagas is not None:
            with st.expander("⚙️ Configurar Colunas (Pagas)", expanded=True):
                col_data_p = selecionar_coluna(df_pagas, "Data Pagamento/Baixa", "pagas_data", ['pagamento', 'baixa', 'data'])
                col_val_p = selecionar_coluna(df_pagas, "Valor Pago", "pagas_valor", ['valor pago', 'valor', 'total'])
                col_desc_p = selecionar_coluna(df_pagas, "Descrição/Fornecedor", "pagas_desc", ['fornecedor', 'descrição', 'nome'])

            # Processamento
            try:
                # Converter Data
                df_pagas[col_data_p] = pd.to_datetime(df_pagas[col_data_p], dayfirst=True, errors='coerce')
                # Limpar Valor
                df_pagas['valor_tratado'] = df_pagas[col_val_p].apply(limpar_valor_moeda)

                # Filtrar data
                mask_p = (df_pagas[col_data_p].dt.date >= inicio_semana_passada) & \
                         (df_pagas[col_data_p].dt.date <= fim_semana_passada)
                df_pagas_final = df_pagas[mask_p].copy()

                total_pago = df_pagas_final['valor_tratado'].sum()
                st.metric("Total Pago", formatar_moeda_br(total_pago))

                # Lista top 3
                top_3 = df_pagas_final.nlargest(3, 'valor_tratado')
                lista_pagas = ""
                for _, row in top_3.iterrows():
                    lista_pagas += f"▫️ {row[col_desc_p]}: {formatar_moeda_br(row['valor_tratado'])}\n"
            except Exception as e:
                st.error(f"Erro ao processar dados: {e}")
    else:
        st.warning("Aguardando arquivo...")

# --- BLOCO 2: CONTAS A PAGAR ---
with col2:
    st.subheader("📅 Previsão (Esta Semana)")
    if arquivo_apagar:
        df_apagar = carregar_dados(arquivo_apagar)
        if df_apagar is not None:
            with st.expander("⚙️ Configurar Colunas (A Pagar)", expanded=True):
                col_data_a = selecionar_coluna(df_apagar, "Data Vencimento", "apagar_data", ['vencimento', 'data'])
                col_val_a = selecionar_coluna(df_apagar, "Valor Líquido/Aberto", "apagar_valor", ['valor líquido', 'valor', 'aberto'])
                col_desc_a = selecionar_coluna(df_apagar, "Descrição/Fornecedor", "apagar_desc", ['fornecedor', 'descrição', 'nome'])

            # Processamento
            try:
                # Converter Data
                df_apagar[col_data_a] = pd.to_datetime(df_apagar[col_data_a], dayfirst=True, errors='coerce')
                # Limpar Valor
                df_apagar['valor_tratado'] = df_apagar[col_val_a].apply(limpar_valor_moeda)

                # Filtrar data
                mask_a = (df_apagar[col_data_a].dt.date >= inicio_semana_atual) & \
                         (df_apagar[col_data_a].dt.date <= fim_semana_atual)
                df_apagar_final = df_apagar[mask_a].copy()

                total_a_pagar = df_apagar_final['valor_tratado'].sum()
                st.metric("Total a Vencer", formatar_moeda_br(total_a_pagar))

            except Exception as e:
                st.error(f"Erro ao processar dados: {e}")
    else:
        st.warning("Aguardando arquivo...")

# --- GERAÇÃO DO TEXTO ---
if arquivo_pagas and arquivo_apagar:
    st.markdown("---")
    st.subheader("📲 Texto para WhatsApp")

    # Tratamento para caso não haja dados nas datas filtradas
    if lista_pagas == "": lista_pagas = "▫️ Sem pagamentos relevantes.\n"
    qtd_boletos = len(df_apagar_final)

    mensagem = f"""Bom dia! ☀️
Segue o resumo financeiro semanal.

✅ *REALIZADO (Semana Passada)*
Total Pago: *{formatar_moeda_br(total_pago)}*
Principais saídas:
{lista_pagas}
📅 *PREVISÃO (Esta Semana)*
Total a Vencer: *{formatar_moeda_br(total_a_pagar)}*
Qtd. boletos: {qtd_boletos}

📎 *Segue em anexo o relatório detalhado.*
Dúvidas, estou à disposição!"""

    st.text_area("Copie o texto abaixo:", value=mensagem, height=350)

    # VISUALIZAÇÃO DAS TABELAS (Opcional)
    with st.expander("🔍 Conferir Tabelas Filtradas"):
        if not df_pagas_final.empty:
            st.write("Detalhes Pagos:")
            st.dataframe(df_pagas_final[[col_data_p, col_desc_p, 'valor_tratado']])
        if not df_apagar_final.empty:
            st.write("Detalhes A Pagar:")
            st.dataframe(df_apagar_final[[col_data_a, col_desc_a, 'valor_tratado']])