# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo v8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16EzVCahGckUcBlixB9bElx42he1-XezL
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime, timedelta
from io import BytesIO
from fpdf import FPDF

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(
    page_title="Relatório Financeiro Corporativo",
    page_icon="💼",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- ESTILOS CSS (Visual Premium) ---
st.markdown("""
    <style>
    /* Container Principal */
    .report-container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 12px;
        border: 1px solid #e0e0e0;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        margin-bottom: 20px;
    }

    /* Títulos */
    .report-title {
        font-family: 'Helvetica Neue', sans-serif;
        color: #1f2937;
        font-size: 28px;
        font-weight: 700;
    }
    .report-subtitle {
        color: #6b7280;
        font-size: 16px;
        margin-top: 5px;
    }

    /* KPIs */
    div[data-testid="stMetric"] {
        background-color: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 15px;
        box-shadow: 0 1px 2px rgba(0,0,0,0.05);
    }

    /* Modo Apresentação */
    .big-kpi {
        font-size: 3rem;
        font-weight: bold;
        color: #1e3a8a;
    }
    </style>
    """, unsafe_allow_html=True)

# --- FUNÇÕES AUXILIARES ---
def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith('.xlsx') or uploaded_file.name.endswith('.xls'):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except Exception as e:
        st.error(f"Erro ao ler arquivo: {e}")
        return None

def limpar_valor_moeda(valor):
    val_float = 0.0
    if isinstance(valor, (int, float)):
        val_float = float(valor)
    elif isinstance(valor, str):
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: val_float = float(limpo)
        except: val_float = 0.0
    return abs(val_float)

def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def selecionar_coluna(df, label, key_suffix, keywords):
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break
    return st.selectbox(f"Coluna de **{label}**:", cols, index=default_idx, key=f"sel_{key_suffix}")

# --- GERADOR DE PDF ---
class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Relatorio Financeiro Semanal', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Pagina {self.page_no()}', 0, 0, 'C')

def criar_pdf(kpis, top_pagos, top_apagar, periodo_txt):
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Período
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, f"Periodo: {periodo_txt}", 0, 1, 'C')
    pdf.ln(10)

    # KPIs
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Resumo Executivo", 0, 1)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Total Pago (Semana Passada): {kpis['pago']}", 0, 1)
    pdf.cell(0, 10, f"A Pagar (Esta Semana): {kpis['apagar']}", 0, 1)
    pdf.cell(0, 10, f"Variacao de Fluxo: {kpis['diff']}", 0, 1)
    pdf.ln(10)

    # Top Pagos
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Maiores Pagamentos Realizados", 0, 1)
    pdf.set_font("Arial", size=10)
    # Cabeçalho Tabela
    pdf.set_fill_color(200, 220, 255)
    pdf.cell(100, 8, "Fornecedor", 1, 0, 'L', 1)
    pdf.cell(50, 8, "Valor", 1, 1, 'R', 1)
    # Dados
    if not top_pagos.empty:
        for _, row in top_pagos.iterrows():
            nome = str(row['Fornecedor'])[:40] # Corta nome longo
            # Tenta tratar encoding latin-1 para fpdf simples
            try: nome = nome.encode('latin-1', 'replace').decode('latin-1')
            except: pass

            pdf.cell(100, 8, nome, 1, 0, 'L')
            pdf.cell(50, 8, formatar_moeda_br(row['valor_tratado']), 1, 1, 'R')
    else:
        pdf.cell(0, 8, "Sem dados.", 1, 1)
    pdf.ln(10)

    # Top A Pagar
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Principais Vencimentos (Esta Semana)", 0, 1)
    pdf.set_font("Arial", size=10)
    pdf.set_fill_color(255, 240, 200)
    pdf.cell(30, 8, "Data", 1, 0, 'C', 1)
    pdf.cell(80, 8, "Fornecedor", 1, 0, 'L', 1)
    pdf.cell(40, 8, "Valor", 1, 1, 'R', 1)

    if not top_apagar.empty:
        for _, row in top_apagar.iterrows():
            nome = str(row['Fornecedor'])[:30]
            try: nome = nome.encode('latin-1', 'replace').decode('latin-1')
            except: pass

            data = row['Vencimento'].strftime('%d/%m') if pd.notnull(row['Vencimento']) else "-"

            pdf.cell(30, 8, data, 1, 0, 'C')
            pdf.cell(80, 8, nome, 1, 0, 'L')
            pdf.cell(40, 8, formatar_moeda_br(row['valor_tratado']), 1, 1, 'R')

    return pdf.output(dest='S').encode('latin-1')

# --- GRÁFICOS ---
def criar_grafico_barras(df, x_col, y_col, cor, titulo):
    base = alt.Chart(df, title=titulo).encode(
        x=alt.X(x_col, axis=alt.Axis(format='%d/%m', title=None, labelAngle=0)),
        y=alt.Y(y_col, axis=alt.Axis(labels=False, title=None, grid=False)),
        tooltip=[alt.Tooltip(x_col, format='%d/%m'), alt.Tooltip(y_col, format=',.2f')]
    )
    barras = base.mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3, size=30).encode(color=alt.value(cor))
    textos = base.mark_text(dy=-10, color='#333', size=12).encode(text=alt.Text(y_col, format=',.0f'))
    return (barras + textos).properties(height=250)

def criar_grafico_ranking(df, cat_col, val_col, titulo, cor):
    top_df = df.groupby(cat_col)[val_col].sum().reset_index().nlargest(5, val_col)
    base = alt.Chart(top_df, title=titulo).encode(
        x=alt.X(val_col, axis=alt.Axis(labels=False, title=None, grid=False)),
        y=alt.Y(cat_col, sort='-x', title=None, axis=alt.Axis(labelLimit=180)),
        tooltip=[cat_col, alt.Tooltip(val_col, format=',.2f')]
    )
    barras = base.mark_bar(cornerRadiusTopRight=3, cornerRadiusBottomRight=3).encode(color=alt.value(cor))
    textos = base.mark_text(align='left', dx=5, color='#333').encode(text=alt.Text(val_col, format=',.0f'))
    return (barras + textos).properties(height=250)

# --- INTERFACE PRINCIPAL ---

# SIDEBAR
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/272/272525.png", width=50)
    st.header("Controles")

    # Switch de Modo Apresentação
    modo_apresentacao = st.toggle("📺 Modo Apresentação", value=False)

    if not modo_apresentacao:
        st.markdown("### Configuração")
        logo_file = st.file_uploader("Logo (Opcional)", type=['png', 'jpg'])
        data_ref = st.date_input("Data Referência", datetime.now())

        # Datas
        inicio_semana_atual = data_ref - timedelta(days=data_ref.weekday())
        fim_semana_atual = inicio_semana_atual + timedelta(days=6)
        inicio_semana_passada = inicio_semana_atual - timedelta(days=7)
        fim_semana_passada = inicio_semana_atual - timedelta(days=1)

        st.markdown("---")
        st.markdown("### Upload Arquivos")
        arquivo_pagas = st.file_uploader("Contas PAGAS", type=['csv', 'xlsx'])
        arquivo_apagar = st.file_uploader("Contas A PAGAR", type=['csv', 'xlsx'])
    else:
        # Se estiver em modo apresentação, usa defaults ou o que já foi carregado
        data_ref = datetime.now()
        inicio_semana_atual = data_ref - timedelta(days=data_ref.weekday())
        fim_semana_atual = inicio_semana_atual + timedelta(days=6)
        inicio_semana_passada = inicio_semana_atual - timedelta(days=7)
        fim_semana_passada = inicio_semana_atual - timedelta(days=1)
        arquivo_pagas = st.session_state.get('arquivo_pagas_cache')
        arquivo_apagar = st.session_state.get('arquivo_apagar_cache')
        logo_file = None # Simplifica na apresentação

    str_passada = f"{inicio_semana_passada.strftime('%d/%m')} a {fim_semana_passada.strftime('%d/%m')}"
    str_atual = f"{inicio_semana_atual.strftime('%d/%m')} a {fim_semana_atual.strftime('%d/%m')}"

# CACHE DE ARQUIVOS (Para persistir entre toggles de modo)
if 'arquivo_pagas' in locals() and arquivo_pagas: st.session_state['arquivo_pagas_cache'] = arquivo_pagas
if 'arquivo_apagar' in locals() and arquivo_apagar: st.session_state['arquivo_apagar_cache'] = arquivo_apagar

# VARIÁVEIS GLOBAIS
total_pago = 0.0
total_a_pagar = 0.0
df_pagas_final = pd.DataFrame()
df_apagar_final = pd.DataFrame()

# --- PROCESSAMENTO ---
if arquivo_pagas and arquivo_apagar:

    # Configuração Colunas (Escondido no modo apresentação)
    if not modo_apresentacao:
        with st.sidebar.expander("🔧 Mapeamento de Colunas", expanded=False):
            st.markdown("**Contas Pagas**")
            df_pagas = carregar_dados(arquivo_pagas)
            if df_pagas is not None:
                col_data_p = selecionar_coluna(df_pagas, "Data", "pagas_data", ['pagamento', 'baixa', 'data'])
                col_val_p = selecionar_coluna(df_pagas, "Valor", "pagas_valor", ['valor pago', 'valor', 'total'])
                col_desc_p = selecionar_coluna(df_pagas, "Nome", "pagas_desc", ['fornecedor', 'nome', 'razão'])
                col_cat_p = selecionar_coluna(df_pagas, "Categoria", "pagas_cat", ['categoria', 'classificação', 'descrição'])

                df_pagas[col_data_p] = pd.to_datetime(df_pagas[col_data_p], dayfirst=True, errors='coerce')
                df_pagas['valor_tratado'] = df_pagas[col_val_p].apply(limpar_valor_moeda)
                mask_p = (df_pagas[col_data_p].dt.date >= inicio_semana_passada) & (df_pagas[col_data_p].dt.date <= fim_semana_passada)
                df_pagas_final = df_pagas[mask_p].copy()
                total_pago = df_pagas_final['valor_tratado'].sum()

            st.markdown("---")
            st.markdown("**Contas A Pagar**")
            df_apagar = carregar_dados(arquivo_apagar)
            if df_apagar is not None:
                col_data_a = selecionar_coluna(df_apagar, "Data", "apagar_data", ['vencimento', 'data'])
                col_val_a = selecionar_coluna(df_apagar, "Valor", "apagar_valor", ['valor líquido', 'valor', 'aberto'])
                col_desc_a = selecionar_coluna(df_apagar, "Nome", "apagar_desc", ['fornecedor', 'nome', 'razão'])
                col_cat_a = selecionar_coluna(df_apagar, "Categoria", "apagar_cat", ['categoria', 'classificação', 'descrição'])

                df_apagar[col_data_a] = pd.to_datetime(df_apagar[col_data_a], dayfirst=True, errors='coerce')
                df_apagar['valor_tratado'] = df_apagar[col_val_a].apply(limpar_valor_moeda)
                mask_a = (df_apagar[col_data_a].dt.date >= inicio_semana_atual) & (df_apagar[col_data_a].dt.date <= fim_semana_atual)
                df_apagar_final = df_apagar[mask_a].copy()
                total_a_pagar = df_apagar_final['valor_tratado'].sum()
    else:
        # Lógica duplicada simplificada para Modo Apresentação (Assumindo que já foi mapeado antes ou usa padrão)
        # Nota: Num app real, usaríamos Session State para persistir o nome das colunas selecionadas.
        # Aqui vamos re-carregar tentando adivinhar para não complicar demais o código.
        df_pagas = carregar_dados(arquivo_pagas)
        df_apagar = carregar_dados(arquivo_apagar)
        # ... (repetir lógica de processamento simplificada ou usar st.session_state para colunas)
        # Para garantir robustez neste exemplo rápido, vamos pedir ao usuário que configure antes de entrar no modo apresentação
        if 'pagas_data' not in st.session_state:
             st.warning("⚠️ Por favor, saia do Modo Apresentação e configure as colunas na barra lateral primeiro.")
             st.stop()

        # Re-processamento usando Session State salvo pelo selectbox
        # (O Streamlit salva a key do selectbox no session_state)
        # Pagas
        df_pagas[st.session_state.sel_pagas_data] = pd.to_datetime(df_pagas[st.session_state.sel_pagas_data], dayfirst=True, errors='coerce')
        df_pagas['valor_tratado'] = df_pagas[st.session_state.sel_pagas_valor].apply(limpar_valor_moeda)
        mask_p = (df_pagas[st.session_state.sel_pagas_data].dt.date >= inicio_semana_passada) & (df_pagas[st.session_state.sel_pagas_data].dt.date <= fim_semana_passada)
        df_pagas_final = df_pagas[mask_p].copy()
        total_pago = df_pagas_final['valor_tratado'].sum()

        # A Pagar
        df_apagar[st.session_state.sel_apagar_data] = pd.to_datetime(df_apagar[st.session_state.sel_apagar_data], dayfirst=True, errors='coerce')
        df_apagar['valor_tratado'] = df_apagar[st.session_state.sel_apagar_valor].apply(limpar_valor_moeda)
        mask_a = (df_apagar[st.session_state.sel_apagar_data].dt.date >= inicio_semana_atual) & (df_apagar[st.session_state.sel_apagar_data].dt.date <= fim_semana_atual)
        df_apagar_final = df_apagar[mask_a].copy()
        total_a_pagar = df_apagar_final['valor_tratado'].sum()

        # Mapeamento de nomes para gráficos
        col_data_p, col_desc_p = st.session_state.sel_pagas_data, st.session_state.sel_pagas_desc
        col_data_a, col_desc_a = st.session_state.sel_apagar_data, st.session_state.sel_apagar_desc

    # --- LAYOUT PRINCIPAL ---

    # Container unificado
    with st.container():
        st.markdown('<div class="report-container">', unsafe_allow_html=True)

        # Cabeçalho
        if not modo_apresentacao:
            c1, c2 = st.columns([3, 1])
            with c1:
                st.markdown('<div class="report-title">Relatório de Fluxo Semanal</div>', unsafe_allow_html=True)
                st.markdown(f'<div class="report-subtitle">📅 {str_passada} e {str_atual}</div>', unsafe_allow_html=True)
            with c2:
                if 'logo_file' in locals() and logo_file: st.image(logo_file, width=150)
        else:
            st.markdown('<h1 style="text-align: center; color: #1e3a8a;">Apresentação de Resultados</h1>', unsafe_allow_html=True)
            st.markdown(f'<p style="text-align: center;">Período: {str_passada} vs {str_atual}</p>', unsafe_allow_html=True)
            st.divider()

        # KPIs
        col_kpi1, col_kpi2, col_kpi3 = st.columns(3)
        col_kpi1.metric("PAGO (Semana Passada)", formatar_moeda_br(total_pago), delta="Executado")
        col_kpi2.metric("A PAGAR (Esta Semana)", formatar_moeda_br(total_a_pagar), delta="Previsão", delta_color="inverse")

        diff = total_a_pagar - total_pago
        msg_diff = "Aumentará pagamentos" if diff > 0 else "Reduzirá pagamentos"
        color_diff = "inverse" if diff > 0 else "normal"
        col_kpi3.metric("Fluxo vs Semana Passada", formatar_moeda_br(abs(diff)), delta=msg_diff, delta_color=color_diff)

        st.markdown("---")

        # Gráficos
        c_g1, c_g2 = st.columns(2)
        with c_g1:
            if not df_pagas_final.empty:
                chart_data_p = df_pagas_final.groupby(col_data_p)['valor_tratado'].sum().reset_index()
                st.altair_chart(criar_grafico_barras(chart_data_p, col_data_p, 'valor_tratado', '#10b981', "Evolução Pagamentos"), use_container_width=True)
            else:
                st.info("Sem dados.")
        with c_g2:
            if not df_apagar_final.empty:
                chart_data_a = df_apagar_final.groupby(col_data_a)['valor_tratado'].sum().reset_index()
                st.altair_chart(criar_grafico_barras(chart_data_a, col_data_a, 'valor_tratado', '#f59e0b', "Previsão Diária"), use_container_width=True)
            else:
                st.info("Sem dados.")

        if modo_apresentacao:
            st.markdown("---")
            st.subheader("Maiores Impactos da Semana")
            # No modo apresentação, mostramos os rankings lado a lado grandes
            c_r1, c_r2 = st.columns(2)
            with c_r1:
                if not df_pagas_final.empty:
                    st.altair_chart(criar_grafico_ranking(df_pagas_final, col_desc_p, 'valor_tratado', 'Top Pagos', '#3b82f6'), use_container_width=True)
            with c_r2:
                if not df_apagar_final.empty:
                    st.altair_chart(criar_grafico_ranking(df_apagar_final, col_desc_a, 'valor_tratado', 'Top A Pagar', '#ef4444'), use_container_width=True)

        st.markdown('</div>', unsafe_allow_html=True)

    # --- ÁREAS EXTRAS (Só aparecem se NÃO estiver em modo apresentação) ---
    if not modo_apresentacao:

        # 1. BOTÃO DOWNLOAD PDF
        st.subheader("📤 Exportar Relatório")

        # Prepara dados para o PDF
        kpis_pdf = {
            'pago': formatar_moeda_br(total_pago),
            'apagar': formatar_moeda_br(total_a_pagar),
            'diff': formatar_moeda_br(abs(diff)) + (" (Aumento)" if diff > 0 else " (Redução)")
        }

        # Prepara tabelas para o PDF (Renomeando colunas para ficar bonito)
        top_pagos_pdf = pd.DataFrame()
        if not df_pagas_final.empty:
            top_pagos_pdf = df_pagas_final.nlargest(5, 'valor_tratado')[[col_desc_p, 'valor_tratado']].rename(columns={col_desc_p: 'Fornecedor'})

        top_apagar_pdf = pd.DataFrame()
        if not df_apagar_final.empty:
            top_apagar_pdf = df_apagar_final.nlargest(5, 'valor_tratado')[[col_data_a, col_desc_a, 'valor_tratado']].rename(columns={col_data_a: 'Vencimento', col_desc_a: 'Fornecedor'})

        if st.button("📄 Gerar PDF do Relatório"):
            try:
                pdf_bytes = criar_pdf(kpis_pdf, top_pagos_pdf, top_apagar_pdf, f"{str_passada} e {str_atual}")
                st.download_button(label="⬇️ Baixar PDF", data=pdf_bytes, file_name="relatorio_financeiro.pdf", mime='application/pdf')
                st.success("PDF Gerado com sucesso! Clique no botão acima para baixar.")
            except Exception as e:
                st.error(f"Erro ao gerar PDF: {e}")

        # 2. DETALHAMENTO E WHATSAPP
        tab1, tab2 = st.tabs(["📋 Tabelas Detalhadas", "📲 Texto WhatsApp"])

        with tab1:
            if not df_pagas_final.empty:
                st.caption("Pagos Semana Passada")
                st.dataframe(df_pagas_final[[col_data_p, col_desc_p, 'valor_tratado']].sort_values(col_data_p), use_container_width=True, hide_index=True)
            if not df_apagar_final.empty:
                st.caption("A Pagar Esta Semana")
                st.dataframe(df_apagar_final[[col_data_a, col_desc_a, 'valor_tratado']].sort_values(col_data_a), use_container_width=True, hide_index=True)

        with tab2:
            top_3 = df_pagas_final.nlargest(3, 'valor_tratado') if not df_pagas_final.empty else pd.DataFrame()
            lista_pagas = ""
            if not top_3.empty:
                for _, row in top_3.iterrows():
                    lista_pagas += f"▫️ {row[col_desc_p]}: {formatar_moeda_br(row['valor_tratado'])}\n"
            else:
                lista_pagas = "▫️ Sem destaques.\n"

            mensagem = f"""Bom dia! ☀️
*Resumo Financeiro Semanal*

✅ *REALIZADO ({str_passada})*
Total Pago: *{formatar_moeda_br(total_pago)}*

Principais saídas:
{lista_pagas}

📅 *PREVISÃO ({str_atual})*
Total a Vencer: *{formatar_moeda_br(total_a_pagar)}*
Qtd. boletos: {len(df_apagar_final)}

Qualquer dúvida, estou à disposição!"""
            st.text_area("Copiar:", value=mensagem, height=300)

else:
    if not modo_apresentacao:
        st.info("👋 Faça o upload dos arquivos na barra lateral para começar.")