# -*- coding: utf-8 -*-
"""Relatório Semanal Nibo vFinal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWgim0H_ADhpPe593p6g0L7FHankH-T2
"""

import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime, timedelta
from PIL import Image

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(
    page_title="Relatório Financeiro Corporativo",
    page_icon="💼",
    layout="wide"
)

# --- ESTILOS CSS (Visual Premium & Print Friendly) ---
st.markdown("""
    <style>
    /* Container Principal do Relatório */
    .report-container {
        background-color: #ffffff;
        padding: 30px;
        border-radius: 12px;
        border: 1px solid #e0e0e0;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        margin-bottom: 20px;
    }

    /* Títulos */
    .report-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 2px solid #3b82f6;
        padding-bottom: 15px;
        margin-bottom: 20px;
    }
    .report-title {
        font-family: 'Helvetica Neue', sans-serif;
        color: #1f2937;
        font-size: 26px;
        font-weight: 700;
    }
    .report-subtitle {
        color: #6b7280;
        font-size: 14px;
        margin-top: 5px;
    }

    /* Métricas (KPIs) */
    div[data-testid="stMetric"] {
        background-color: #f8fafc;
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 15px;
        box-shadow: 0 1px 2px rgba(0,0,0,0.05);
    }
    div[data-testid="stMetricLabel"] {
        font-size: 13px;
        font-weight: 600;
        color: #64748b;
        text-transform: uppercase;
    }
    div[data-testid="stMetricValue"] {
        font-size: 24px;
        color: #0f172a;
    }
    </style>
    """, unsafe_allow_html=True)

# --- FUNÇÕES AUXILIARES ---
def carregar_dados(uploaded_file):
    try:
        if uploaded_file.name.endswith('.xlsx') or uploaded_file.name.endswith('.xls'):
            return pd.read_excel(uploaded_file)
        else:
            try: return pd.read_csv(uploaded_file, sep=',', encoding='utf-8')
            except: return pd.read_csv(uploaded_file, sep=';', encoding='latin1')
    except Exception as e:
        st.error(f"Erro ao ler arquivo: {e}")
        return None

def limpar_valor_moeda(valor):
    """Retorna sempre o valor absoluto (positivo) para gráficos e somas"""
    val_float = 0.0
    if isinstance(valor, (int, float)):
        val_float = float(valor)
    elif isinstance(valor, str):
        limpo = valor.replace('R$', '').replace(' ', '').replace('.', '').replace(',', '.')
        try: val_float = float(limpo)
        except: val_float = 0.0
    return abs(val_float)

def formatar_moeda_br(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def selecionar_coluna(df, label, key_suffix, keywords):
    cols = list(df.columns)
    default_idx = 0
    for i, col in enumerate(cols):
        if any(k in col.lower() for k in keywords):
            default_idx = i
            break
    return st.selectbox(f"Coluna de **{label}**:", cols, index=default_idx, key=f"sel_{key_suffix}")

# --- GRÁFICOS ---
def criar_grafico_barras(df, x_col, y_col, cor, titulo):
    base = alt.Chart(df, title=titulo).encode(
        x=alt.X(x_col, axis=alt.Axis(format='%d/%m', title=None, labelAngle=0)),
        y=alt.Y(y_col, axis=alt.Axis(labels=False, title=None, grid=False)),
        tooltip=[alt.Tooltip(x_col, format='%d/%m'), alt.Tooltip(y_col, format=',.2f')]
    )
    barras = base.mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3, size=30).encode(color=alt.value(cor))
    textos = base.mark_text(dy=-10, color='#333', size=12).encode(text=alt.Text(y_col, format=',.0f'))
    return (barras + textos).properties(height=200)

def criar_grafico_ranking(df, cat_col, val_col, titulo, cor):
    top_df = df.groupby(cat_col)[val_col].sum().reset_index().nlargest(5, val_col)
    base = alt.Chart(top_df, title=titulo).encode(
        x=alt.X(val_col, axis=alt.Axis(labels=False, title=None, grid=False)),
        y=alt.Y(cat_col, sort='-x', title=None, axis=alt.Axis(labelLimit=180)),
        tooltip=[cat_col, alt.Tooltip(val_col, format=',.2f')]
    )
    barras = base.mark_bar(cornerRadiusTopRight=3, cornerRadiusBottomRight=3).encode(color=alt.value(cor))
    textos = base.mark_text(align='left', dx=5, color='#333').encode(text=alt.Text(val_col, format=',.0f'))
    return (barras + textos).properties(height=220)

# --- INTERFACE PRINCIPAL ---

# 1. SIDEBAR (CONTROLES)
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/272/272525.png", width=50) # Ícone genérico
    st.header("Painel de Controle")

    st.markdown("### 1. Configuração")
    # Upload da Logo
    logo_file = st.file_uploader("Sua Logo (Opcional)", type=['png', 'jpg', 'jpeg'])
    data_ref = st.date_input("Data de Referência", datetime.now())

    # Datas
    inicio_semana_atual = data_ref - timedelta(days=data_ref.weekday())
    fim_semana_atual = inicio_semana_atual + timedelta(days=6)
    inicio_semana_passada = inicio_semana_atual - timedelta(days=7)
    fim_semana_passada = inicio_semana_atual - timedelta(days=1)

    str_passada = f"{inicio_semana_passada.strftime('%d/%m')} a {fim_semana_passada.strftime('%d/%m')}"
    str_atual = f"{inicio_semana_atual.strftime('%d/%m')} a {fim_semana_atual.strftime('%d/%m')}"

    st.markdown("---")
    st.markdown("### 2. Dados Financeiros")
    arquivo_pagas = st.file_uploader("Contas PAGAS (Semana Passada)", type=['csv', 'xlsx'])
    arquivo_apagar = st.file_uploader("Contas A PAGAR (Esta Semana)", type=['csv', 'xlsx'])

# VARIÁVEIS GLOBAIS
total_pago = 0.0
total_a_pagar = 0.0
df_pagas_final = pd.DataFrame()
df_apagar_final = pd.DataFrame()

# --- PROCESSAMENTO ---
if arquivo_pagas and arquivo_apagar:

    # Processamento silencioso
    with st.sidebar.expander("🔧 Ajuste de Colunas (Avançado)", expanded=False):
        st.markdown("**Contas Pagas**")
        df_pagas = carregar_dados(arquivo_pagas)
        if df_pagas is not None:
            col_data_p = selecionar_coluna(df_pagas, "Data Pagamento", "pagas_data", ['pagamento', 'baixa', 'data'])
            col_val_p = selecionar_coluna(df_pagas, "Valor", "pagas_valor", ['valor pago', 'valor', 'total'])
            col_desc_p = selecionar_coluna(df_pagas, "Fornecedor", "pagas_desc", ['fornecedor', 'descrição', 'nome'])

            df_pagas[col_data_p] = pd.to_datetime(df_pagas[col_data_p], dayfirst=True, errors='coerce')
            df_pagas['valor_tratado'] = df_pagas[col_val_p].apply(limpar_valor_moeda)
            mask_p = (df_pagas[col_data_p].dt.date >= inicio_semana_passada) & (df_pagas[col_data_p].dt.date <= fim_semana_passada)
            df_pagas_final = df_pagas[mask_p].copy()
            total_pago = df_pagas_final['valor_tratado'].sum()

        st.markdown("---")
        st.markdown("**Contas A Pagar**")
        df_apagar = carregar_dados(arquivo_apagar)
        if df_apagar is not None:
            col_data_a = selecionar_coluna(df_apagar, "Data Vencimento", "apagar_data", ['vencimento', 'data'])
            col_val_a = selecionar_coluna(df_apagar, "Valor", "apagar_valor", ['valor líquido', 'valor', 'aberto'])
            col_desc_a = selecionar_coluna(df_apagar, "Fornecedor", "apagar_desc", ['fornecedor', 'descrição', 'nome'])

            df_apagar[col_data_a] = pd.to_datetime(df_apagar[col_data_a], dayfirst=True, errors='coerce')
            df_apagar['valor_tratado'] = df_apagar[col_val_a].apply(limpar_valor_moeda)
            mask_a = (df_apagar[col_data_a].dt.date >= inicio_semana_atual) & (df_apagar[col_data_a].dt.date <= fim_semana_atual)
            df_apagar_final = df_apagar[mask_a].copy()
            total_a_pagar = df_apagar_final['valor_tratado'].sum()

    # --- ÁREA DE RELATÓRIO VISUAL ---
    with st.container():
        # Abertura do container CSS
        st.markdown('<div class="report-container">', unsafe_allow_html=True)

        # 1. CABEÇALHO COM LOGO
        col_header_txt, col_header_img = st.columns([3, 1])
        with col_header_txt:
            st.markdown('<div class="report-title">Relatório de Fluxo Semanal</div>', unsafe_allow_html=True)
            st.markdown(f'<div class="report-subtitle">📅 Período de Análise: {str_passada} a {str_atual}</div>', unsafe_allow_html=True)
        with col_header_img:
            if logo_file:
                st.image(logo_file, width=150)

        st.markdown("---")

        # 2. KPIs (Métricas)
        col_kpi1, col_kpi2, col_kpi3 = st.columns(3)
        col_kpi1.metric("TOTAL PAGO (Semana Passada)", formatar_moeda_br(total_pago), delta="Executado")
        col_kpi2.metric("A PAGAR (Esta Semana)", formatar_moeda_br(total_a_pagar), delta="Previsão", delta_color="inverse")

        diff = total_a_pagar - total_pago
        if diff > 0:
            msg_diff = "Aumentará pagamentos"
            color_diff = "inverse"
        elif diff < 0:
            msg_diff = "Reduzirá pagamentos"
            color_diff = "normal"
        else:
            msg_diff = "Estável"
            color_diff = "off"
        col_kpi3.metric("Comparativo de Fluxo", formatar_moeda_br(abs(diff)), delta=msg_diff, delta_color=color_diff)

        st.write("") # Espaçamento

        # 3. GRÁFICOS
        c_g1, c_g2 = st.columns(2)
        with c_g1:
            if not df_pagas_final.empty:
                chart_data_p = df_pagas_final.groupby(col_data_p)['valor_tratado'].sum().reset_index()
                st.altair_chart(criar_grafico_barras(chart_data_p, col_data_p, 'valor_tratado', '#10b981', "Evolução Pagamentos (Dia a Dia)"), use_container_width=True)
            else:
                st.info("Sem pagamentos.")

        with c_g2:
            if not df_apagar_final.empty:
                chart_data_a = df_apagar_final.groupby(col_data_a)['valor_tratado'].sum().reset_index()
                st.altair_chart(criar_grafico_barras(chart_data_a, col_data_a, 'valor_tratado', '#f59e0b', "Previsão de Saída (Por Vencimento)"), use_container_width=True)
            else:
                st.info("Sem contas a vencer.")

        # 4. TABELAS TÁTICAS (Radar de Contas)
        st.markdown("---")
        c_t1, c_t2 = st.columns(2)

        with c_t1:
            st.markdown("#### 🏆 Top Pagamentos Realizados")
            if not df_pagas_final.empty:
                st.altair_chart(criar_grafico_ranking(df_pagas_final, col_desc_p, 'valor_tratado', '', '#3b82f6'), use_container_width=True)
            else:
                st.caption("Sem dados.")

        with c_t2:
            st.markdown("#### ⚠️ Radar: Top 5 a Vencer (Esta Semana)")
            if not df_apagar_final.empty:
                # Cria uma tabela limpa apenas com o que importa
                top_vencer = df_apagar_final.nlargest(5, 'valor_tratado')[[col_data_a, col_desc_a, 'valor_tratado']].copy()
                top_vencer[col_data_a] = top_vencer[col_data_a].dt.strftime('%d/%m')
                top_vencer['valor_tratado'] = top_vencer['valor_tratado'].apply(formatar_moeda_br)
                # Renomeia colunas para ficar bonito
                top_vencer.columns = ['Vencimento', 'Fornecedor', 'Valor']
                st.dataframe(top_vencer, hide_index=True, use_container_width=True)
            else:
                st.success("Sem contas críticas para esta semana.")

        st.markdown('</div>', unsafe_allow_html=True) # Fim Container

    # --- TEXTO WHATSAPP ---
    st.markdown("### 📲 Texto para WhatsApp")

    # Lógica Top 3 para o texto
    top_3 = df_pagas_final.nlargest(3, 'valor_tratado')
    lista_pagas = ""
    for _, row in top_3.iterrows():
        lista_pagas += f"▫️ {row[col_desc_p]}: {formatar_moeda_br(row['valor_tratado'])}\n"
    if lista_pagas == "": lista_pagas = "▫️ Sem destaques.\n"

    mensagem = f"""Bom dia! ☀️
*Resumo de Contas Pagas e Previsão*

✅ *REALIZADO ({str_passada})*
Total Pago: *{formatar_moeda_br(total_pago)}*

Principais saídas:
{lista_pagas}

📅 *PREVISÃO ({str_atual})*
Total a Vencer: *{formatar_moeda_br(total_a_pagar)}*
Qtd. boletos: {len(df_apagar_final)}

Qualquer dúvida, estou à disposição!"""

    st.text_area("Copiar mensagem:", value=mensagem, height=300)

else:
    # Tela de Boas Vindas
    st.info("👋 Olá! Faça o upload dos arquivos 'Contas Pagas' e 'Contas a Pagar' na barra lateral.")